import test from 'node:test';
import assert from 'node:assert/strict';
import {loadMaster} from '../src/math-master/load.ts';
import {validateMaster} from '../src/math-master/validate.ts';
import {createLearner} from '../src/math-master/learner.ts';
import {skillAvailable,startUnit,unitStatus} from '../src/math-master/unlock.ts';
import {recordAssessment,completeDiagnostic,planDiagnosticFollowup,confirmStable} from '../src/math-master/diagnosis.ts';
import {saveDiagnosticMaxEvidence,maxEvidence,submitMax} from '../src/math-master/max.ts';
import {beginRepair,finishRepair} from '../src/math-master/repair.ts';
import {selectTask} from '../src/learning/task-selector.ts';
import type {Assessment,MaxAttempt,Master} from '../src/math-master/types.ts';
const m=loadMaster();
const attempt=(day:number,extra:Partial<MaxAttempt>={}):MaxAttempt=>({problemId:`problem-${day}`,independenceKey:`family-${day}`,at:`2026-09-${String(day).padStart(2,'0')}T01:00:00Z`,noHint:true,noMethodSpecified:true,independent:true,examQuality:true,practicalTime:true,correctConclusion:true,readable:true,sufficientWriting:true,...extra});
const assessment=(id:string,extra:Partial<Assessment>={}):Assessment=>({id,problemId:id,skillId:'CAL3',at:attempt(7).at,context:'diagnostic',solved:true,readable:true,independent:true,integration:true,tags:[],dimensions:{understanding:'success',modeling:'success',method:'success',conditions:'success',calculation:'success',expression:'success',conclusion:'success'},crossSkills:{},...extra});
test('A: learning does not unlock; stable does',()=>{const p=createLearner(m);p.skills.CAL1='learning';assert.equal(skillAvailable(m,p,'CAL2'),false);p.skills.CAL1='stable';assert.equal(skillAvailable(m,p,'CAL2'),true);});
test('A: MAX entails stable prerequisites, except a currently diagnosed repair',()=>{const p=createLearner(m);p.maxUnits=['CAL'];assert.equal(skillAvailable(m,p,'EXP1'),true);p.skills.CAL3='needs_repair';assert.equal(skillAvailable(m,p,'EXP1'),false);});
test('B: all required units must be MAX; stable cannot substitute',()=>{const x=structuredClone(m);x.units[6].prerequisites=['HSX','QEQ'];const p=createLearner(x);for(const s of x.skills)p.skills[s.id]='stable';assert.equal(unitStatus(x,p,'QFN'),'LOCKED');p.maxUnits=['HSX'];assert.equal(unitStatus(x,p,'QFN'),'LOCKED');p.maxUnits.push('QEQ');assert.equal(unitStatus(x,p,'QFN'),'OPEN');});
test('C: diagnostic success grants stable only, while MAX-equivalent evidence is reusable',()=>{const p=createLearner(m);for(const day of [7,8]){const a=attempt(day);recordAssessment(m,p,assessment(`d${day}`,{problemId:a.problemId,at:a.at}));saveDiagnosticMaxEvidence(m,p,'CAL',`d${day}`,a);}completeDiagnostic(m,p,[{unitId:'CAL',assessmentIds:['d7','d8']}]);assert.deepEqual(p.maxUnits,[]);assert.equal(p.skills.CAL1,'stable');assert.equal(unitStatus(m,p,'EXP'),'LOCKED');assert.equal(maxEvidence(m,p,'CAL',attempt(8).at).length,2);assert.equal(submitMax(m,p,'CAL',attempt(9)),true);});
test('C: hint, method instruction, missing writing or unreadability cannot become diagnostic MAX evidence',()=>{for(const patch of [{noHint:false},{noMethodSpecified:false},{sufficientWriting:false},{readable:false},{independent:false},{practicalTime:false},{examQuality:false},{correctConclusion:false}]){const p=createLearner(m),a=attempt(7,patch);recordAssessment(m,p,assessment('d',{problemId:a.problemId,at:a.at}));assert.throws(()=>saveDiagnosticMaxEvidence(m,p,'CAL','d',a));assert.deepEqual(p.diagnosticMaxEvidence,{});}});
test('C: source assessment identity, unit and intermediate evaluation are verified',()=>{const p=createLearner(m),a=attempt(7);recordAssessment(m,p,assessment('d',{problemId:a.problemId,dimensions:{understanding:'success',modeling:'success',method:'success',conditions:'partial',calculation:'success',expression:'success',conclusion:'success'}}));assert.throws(()=>saveDiagnosticMaxEvidence(m,p,'CAL','d',a));assert.throws(()=>saveDiagnosticMaxEvidence(m,p,'EXP','d',a));});
test('C: same-day diagnostic evidence is stored but counts only once; duplicate import rejected',()=>{const p=createLearner(m);for(const suffix of ['a','b','c']){const a=attempt(7,{problemId:suffix,independenceKey:suffix});recordAssessment(m,p,assessment(suffix,{problemId:suffix}));saveDiagnosticMaxEvidence(m,p,'CAL',suffix,a);}assert.equal(p.diagnosticMaxEvidence.CAL.length,3);assert.equal(maxEvidence(m,p,'CAL',attempt(7).at).length,1);assert.deepEqual(p.maxUnits,[]);assert.throws(()=>saveDiagnosticMaxEvidence(m,p,'CAL','a',attempt(7,{problemId:'a',independenceKey:'a'})));assert.throws(()=>submitMax(m,p,'CAL',attempt(7)));});
test('C: failed integration diagnoses only the implicated branch without resetting skills',()=>{const p=createLearner(m);p.skills.HSX1='stable';p.skills.CAL1='stable';const before={...p.skills};recordAssessment(m,p,assessment('failed',{skillId:'QFN3',solved:false,tags:['factorization']}));planDiagnosticFollowup(m,p,'failed',['HSX2']);assert.deepEqual(p.skills,before);assert.deepEqual(p.diagnosticPending,['HSX2']);assert.deepEqual(selectTask(m,p),{kind:'diagnostic',skillId:'HSX2'});assert.throws(()=>completeDiagnostic(m,p,[]));recordAssessment(m,p,assessment('probe',{skillId:'HSX2',integration:false}));assert.deepEqual(p.diagnosticPending,[]);completeDiagnostic(m,p,[]);assert.equal(p.skills.HSX1,'stable');assert.deepEqual(p.maxUnits,[]);});
test('C: failing branch can descend further; unrelated diagnostic branch rejected atomically',()=>{const p=createLearner(m);recordAssessment(m,p,assessment('f',{skillId:'HSX2',solved:false}));planDiagnosticFollowup(m,p,'f',['EXP2']);recordAssessment(m,p,assessment('f2',{skillId:'EXP2',solved:false}));planDiagnosticFollowup(m,p,'f2',['CAL2']);assert.deepEqual(p.diagnosticPending,['CAL2']);assert.throws(()=>planDiagnosticFollowup(m,p,'f2',['QFN1']));assert.deepEqual(p.diagnosticPending,['CAL2']);});
test('D: repair preserves activeUnit and returns exact skill/problem; unrelated target rejected',()=>{const p=createLearner(m);p.diagnosticCompleted=true;p.maxUnits=['CAL','EXP','EQU','FUN','HSX','QEQ'];startUnit(m,p,'QFN');for(const id of ['f1','f2'])recordAssessment(m,p,assessment(id,{skillId:'HSX2',context:'practice',solved:false,tags:['factorization']}));const r={sourceSkillId:'QFN1',repairSkillId:'HSX2',returnToSkillId:'QFN1',returnToProblemId:'original'};assert.throws(()=>beginRepair(m,p,{...r,repairSkillId:'QFN3'}));assert.throws(()=>beginRepair(m,p,{...r,returnToSkillId:'CAL1'}));beginRepair(m,p,r);assert.equal(p.activeUnit,'QFN');for(const id of ['s1','s2'])recordAssessment(m,p,assessment(id,{skillId:'HSX2',context:'repair'}));confirmStable(p,'HSX2');finishRepair(p);assert.equal(p.activeUnit,'QFN');assert.deepEqual(selectTask(m,p),{kind:'resume',skillId:'QFN1',problemId:'original'});});
test('E: fewer than three successes never grants MAX; failure preserves stable skills',()=>{const p=createLearner(m);p.skills.CAL1='stable';assert.equal(submitMax(m,p,'CAL',attempt(7)),false);assert.equal(submitMax(m,p,'CAL',attempt(8)),false);assert.equal(submitMax(m,p,'CAL',attempt(9,{correctConclusion:false})),false);assert.deepEqual(p.maxUnits,[]);assert.equal(p.skills.CAL1,'stable');assert.equal(p.activeUnit,'CAL');});
test('E: JST midnight separates days; same day attempts do not increment state',()=>{const p=createLearner(m);submitMax(m,p,'CAL',attempt(7,{at:'2026-09-07T14:59:59Z'}));submitMax(m,p,'CAL',attempt(8,{at:'2026-09-07T15:00:00Z'}));const before=structuredClone(p);assert.throws(()=>submitMax(m,p,'CAL',attempt(9,{at:'2026-09-08T14:59:59Z'})));assert.deepEqual(p,before);});
test('E: first-success window expires exactly at seven days, including later evidence',()=>{const p=createLearner(m);submitMax(m,p,'CAL',attempt(7));submitMax(m,p,'CAL',attempt(8));assert.equal(maxEvidence(m,p,'CAL','2026-09-14T00:59:59.999Z').length,2);assert.equal(maxEvidence(m,p,'CAL','2026-09-14T01:00:00Z').length,0);assert.equal(submitMax(m,p,'CAL',attempt(15)),false);assert.equal(maxEvidence(m,p,'CAL',attempt(15).at).length,1);assert.deepEqual(p.maxUnits,[]);});
test('E: successful MAX materializes stable for all skills of that unit',()=>{const p=createLearner(m);for(const day of [7,8,9])submitMax(m,p,'CAL',attempt(day));for(const s of m.skills.filter(s=>s.unitId==='CAL'))assert.equal(p.skills[s.id],'stable');});
const corruptions:[string,(m:Master)=>void][]=[
 ['missing skill',m=>m.skills[0].prerequisites=['unknown']],
 ['missing unit prerequisite',m=>m.units[0].prerequisites=['unknown']],
 ['missing owning unit',m=>m.skills[0].unitId='unknown'],
 ['skill cycle',m=>{m.skills[0].prerequisites=['CAL2'];m.skills[1].prerequisites=['CAL1'];}],
 ['unit cycle',m=>m.units[0].prerequisites=['EXP']],
 ['skill self-reference',m=>m.skills[0].prerequisites=['CAL1']],
 ['unit self-reference',m=>m.units[0].prerequisites=['CAL']]
];
for(const [label,corrupt] of corruptions)test(`F: rejects ${label}`,()=>{const bad=structuredClone(m);corrupt(bad);assert.throws(()=>validateMaster(bad));});
test('schema: learner can round-trip JSON without losing pending diagnosis or evidence',()=>{const p=createLearner(m),a=attempt(7);recordAssessment(m,p,assessment('d',{problemId:a.problemId}));saveDiagnosticMaxEvidence(m,p,'CAL','d',a);assert.deepEqual(JSON.parse(JSON.stringify(p)),p);assert.equal(p.schemaVersion,1);});
