import test from 'node:test';
import assert from 'node:assert/strict';
import {loadMaster} from '../src/math-master/load.ts';
import {validateMaster} from '../src/math-master/validate.ts';
import {createLearner,beginSession,recordBehavior} from '../src/math-master/learner.ts';
import {unitStatus,skillAvailable,startUnit} from '../src/math-master/unlock.ts';
import {recordAssessment,repairCandidates,confirmStable,completeDiagnostic} from '../src/math-master/diagnosis.ts';
import {beginRepair,finishRepair} from '../src/math-master/repair.ts';
import {submitMax,maxEvidence} from '../src/math-master/max.ts';
import {selectTask} from '../src/learning/task-selector.ts';
import type {Assessment,MaxAttempt} from '../src/math-master/types.ts';
const m=loadMaster();
const assessment=(id:string,skillId='CAL1',extra:Partial<Assessment>={}):Assessment=>({id,problemId:id,skillId,at:'2026-09-07T01:00:00Z',context:'practice',solved:true,readable:true,independent:true,integration:false,tags:[],dimensions:{understanding:'success',modeling:'success',method:'success',conditions:'success',calculation:'success',expression:'success',conclusion:'success'},crossSkills:{X11:'success'},...extra});
const max=(day:number,extra:Partial<MaxAttempt>={}):MaxAttempt=>({problemId:`p${day}`,independenceKey:`family${day}`,at:`2026-09-${String(day).padStart(2,'0')}T01:00:00Z`,noHint:true,noMethodSpecified:true,independent:true,examQuality:true,practicalTime:true,correctConclusion:true,readable:true,sufficientWriting:true,...extra});
test('master: seven units, 21 skills, 13 cross skills, separate policies',()=>{assert.equal(m.units.length,7);assert.equal(m.skills.length,21);assert.equal(m.crossSkills.length,13);assert.equal(m.maxDefinitions.length,7);});
test('reject cycles, missing references, duplicate IDs and cross-layer inconsistency',()=>{
 for(const mutate of [(x:typeof m)=>x.units[0].prerequisites.push('QFN'),(x:typeof m)=>x.skills[0].prerequisites.push('missing'),(x:typeof m)=>x.skills.push(x.skills[0]),(x:typeof m)=>x.skills[0].prerequisites.push('QFN3'),(x:typeof m)=>x.skills[0].crossSkillIds.push('X99'),(x:typeof m)=>x.maxDefinitions.pop()]){const bad=structuredClone(m);mutate(bad);assert.throws(()=>validateMaster(bad));}
});
test('stable opens internal skill but never upper unit; EXP has no effect',()=>{const p=createLearner(m);p.skills.CAL1='stable';assert.ok(skillAvailable(m,p,'CAL2'));assert.equal(unitStatus(m,p,'EXP'),'LOCKED');recordBehavior(p,'start');recordBehavior(p,'start');assert.equal(p.humanExp,1);assert.equal(unitStatus(m,p,'EXP'),'LOCKED');});
test('initial diagnosis skips sections without granting MAX and runs once',()=>{const p=createLearner(m);assert.equal(selectTask(m,p).kind,'diagnostic');for(const id of ['d1','d2'])recordAssessment(m,p,assessment(id,'CAL3',{context:'diagnostic',integration:true}));completeDiagnostic(m,p,[{unitId:'CAL',assessmentIds:['d1','d2']}]);assert.equal(p.skills.CAL1,'stable');assert.deepEqual(p.maxUnits,[]);startUnit(m,p,'CAL');assert.deepEqual(selectTask(m,p),{kind:'max',unitId:'CAL'});assert.throws(()=>completeDiagnostic(m,p,[]));});
test('diagnosis rejects final-answer/ordinary/nonindependent evidence',()=>{const p=createLearner(m);for(const id of ['d1','d2'])recordAssessment(m,p,assessment(id,'CAL3',{context:'diagnostic'}));assert.throws(()=>completeDiagnostic(m,p,[{unitId:'CAL',assessmentIds:['d1','d2']}]));assert.equal(p.diagnosticCompleted,false);});
test('warmup mistake does not demote stable skill',()=>{const p=createLearner(m);p.diagnosticCompleted=true;p.skills.CAL1='stable';p.lastSkillId='CAL1';beginSession(p);assert.equal(selectTask(m,p).kind,'warmup');recordAssessment(m,p,assessment('w','CAL1',{context:'warmup',solved:false,tags:['sign']}));assert.equal(p.skills.CAL1,'stable');assert.equal(p.warmupRemaining,0);assert.deepEqual(repairCandidates(p,'CAL1'),[]);});
test('unreadable becomes unresolved; method evidence retained on calculation failure',()=>{const p=createLearner(m);recordAssessment(m,p,assessment('u','CAL1',{readable:false}));assert.equal(p.assessments[0].solved,false);assert.ok(p.assessments[0].tags.includes('handwriting_unreadable'));recordAssessment(m,p,assessment('c','CAL1',{solved:false,tags:['calculation']}));assert.equal(p.assessments[1].dimensions.method,'success');assert.equal(p.crossSkillEvidence.X11.length,2);});
test('two distinct repeated errors required; targeted repair returns to exact problem',()=>{
 const p=createLearner(m);p.diagnosticCompleted=true;p.maxUnits=['CAL','EXP','EQU','FUN','HSX','QEQ'];for(const s of m.skills)p.skills[s.id]='stable';startUnit(m,p,'QFN');
 const r={sourceSkillId:'QFN3',repairSkillId:'HSX2',returnToSkillId:'QFN3',returnToProblemId:'original-qfn-problem'};
 recordAssessment(m,p,assessment('bad1','HSX2',{solved:false,tags:['factorization']}));assert.throws(()=>beginRepair(m,p,r));assert.equal(p.skills.HSX2,'stable');
 recordAssessment(m,p,assessment('bad2','HSX2',{solved:false,tags:['factorization']}));beginRepair(m,p,r);assert.equal(p.activeUnit,'QFN');assert.equal(selectTask(m,p).kind,'repair');assert.throws(()=>finishRepair(p));
 for(const id of ['fixed1','fixed2'])recordAssessment(m,p,assessment(id,'HSX2',{context:'repair'}));confirmStable(p,'HSX2');finishRepair(p);assert.deepEqual(selectTask(m,p),{kind:'resume',skillId:'QFN3',problemId:'original-qfn-problem'});assert.equal(p.activeUnit,'QFN');
});
test('same problem repeated and warmup cannot establish stable',()=>{const p=createLearner(m);for(const id of ['a','b'])recordAssessment(m,p,assessment(id,'CAL1',{problemId:'same'}));assert.throws(()=>confirmStable(p,'CAL1'));});
test('MAX is available immediately; three days of evidence unlock next unit',()=>{const p=createLearner(m);startUnit(m,p,'CAL');assert.equal(submitMax(m,p,'CAL',max(7)),false);assert.throws(()=>submitMax(m,p,'CAL',max(7,{problemId:'another'})));assert.equal(submitMax(m,p,'CAL',max(8)),false);assert.equal(submitMax(m,p,'CAL',max(9)),true);assert.equal(unitStatus(m,p,'CAL'),'MAX');assert.equal(unitStatus(m,p,'EXP'),'OPEN');assert.equal(p.activeUnit,null);assert.equal(p.humanExp,0);});
test('MAX rejects hints, incomplete writing, repeated family and expires at seven days',()=>{const p=createLearner(m);submitMax(m,p,'CAL',max(7));submitMax(m,p,'CAL',max(8,{independenceKey:'family7'}));submitMax(m,p,'CAL',max(9,{sufficientWriting:false}));submitMax(m,p,'CAL',max(10,{noHint:false}));assert.equal(maxEvidence(m,p,'CAL',max(13).at).length,1);assert.equal(maxEvidence(m,p,'CAL',max(14).at).length,0);submitMax(m,p,'CAL',max(14));assert.equal(maxEvidence(m,p,'CAL',max(14).at).length,1);});
test('activeUnit prohibits lateral movement even if second branch is OPEN',()=>{const branch=structuredClone(m);branch.units[1].prerequisites=[];const p=createLearner(branch);startUnit(branch,p,'CAL');assert.throws(()=>startUnit(branch,p,'EXP'));assert.throws(()=>submitMax(branch,p,'EXP',max(7)));});
test('multi-parent unlock requires every prerequisite MAX',()=>{const branch=structuredClone(m);branch.units[6].prerequisites=['QEQ','HSX'];const p=createLearner(branch);p.maxUnits=['QEQ'];p.skills.HSX3='stable';assert.equal(unitStatus(branch,p,'QFN'),'LOCKED');p.maxUnits.push('HSX');assert.equal(unitStatus(branch,p,'QFN'),'OPEN');});
