import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import baseline from './stage4-hashes.json' with {type:'json'};
import {curriculum as c,master,problems} from '../src/curriculum/master.ts';
import {validateCurriculum} from '../src/curriculum/validate.ts';
import {routeMap} from '../src/curriculum/route-map.ts';
import {createLearner} from '../src/math-master/learner.ts';
import {skillAvailable,unitStatus,startUnit} from '../src/math-master/unlock.ts';
import {submitMax} from '../src/math-master/max.ts';
import type {MaxAttempt} from '../src/math-master/types.ts';
import type {Curriculum} from '../src/curriculum/types.ts';
import {LearningService} from '../src/services/learning-service.ts';
import {LearningApplication} from '../src/application/learning-application.ts';
import {ManualClock} from '../src/application/clock.ts';
import {MemoryLearningRepository} from '../src/persistence/repository.ts';
import {decodeDocument} from '../src/persistence/model.ts';
import {migrateDocument} from '../src/curriculum/migration.ts';
const at='2026-09-07T03:00:00Z';
function ready(unit:string){const p=createLearner(master);p.diagnosticCompleted=true;const ancestors=new Set<string>();function visit(id:string){for(const pre of master.units.find(u=>u.id===id)!.prerequisites){ancestors.add(pre);visit(pre);}}visit(unit);p.maxUnits=[...ancestors];for(const s of master.skills)if(ancestors.has(s.unitId))p.skills[s.id]='stable';return p;}
test('stage 4: all 143 original tests are byte-for-byte preserved',()=>{for(const e of baseline)assert.equal(createHash('sha256').update(readFileSync(new URL(e.Name,import.meta.url))).digest('hex').toUpperCase(),e.Hash,e.Name);});
test('whole catalog: 41 units, 123 skills, 410 fixed problems; validator passes',()=>{validateCurriculum(c);assert.equal(master.units.length,41);assert.equal(master.skills.length,123);assert.equal(problems.length,410);});
test('middle school has six worlds, and HSX does not require all six',()=>{assert.equal(new Set(c.units.filter(u=>u.world.startsWith('中学')).map(u=>u.world)).size,6);assert.ok(!master.units.find(u=>u.id==='HSX')!.prerequisites.includes('MSTAT'));});
for(const unit of master.units){
 test(`${unit.id}: stable unlocks internal skills, learning does not`,()=>{const p=ready(unit.id),ss=master.skills.filter(s=>s.unitId===unit.id);for(const s of ss){for(const pre of s.prerequisites){p.skills[pre]='learning';const inheritedMax=p.maxUnits.includes(master.skills.find(x=>x.id===pre)!.unitId);assert.equal(skillAvailable(master,p,s.id),inheritedMax);p.skills[pre]='stable';}assert.equal(skillAvailable(master,p,s.id),true);p.skills[s.id]='stable';}assert.equal(unitStatus(master,p,unit.id),'OPEN');});
 test(`${unit.id}: every mandatory MAX is necessary; stable is insufficient`,()=>{for(const missing of unit.prerequisites){const p=ready(unit.id);p.maxUnits=p.maxUnits.filter(id=>id!==missing);assert.equal(unitStatus(master,p,unit.id),'LOCKED');p.maxUnits.push(missing);assert.equal(unitStatus(master,p,unit.id),'OPEN');}});
 test(`${unit.id}: all skills have two usable tasks and representative MAX connects to evidence`,()=>{const engine=new LearningService(true,c),cp=engine.exportCheckpoint();cp.learner=ready(unit.id);cp.screen='home';engine.restoreCheckpoint(cp);engine.chooseUnit(unit.id);for(const skill of master.skills.filter(s=>s.unitId===unit.id)){assert.equal(engine.snapshot.problem?.skillId,skill.id);for(let i=0;i<2;i++){engine.submission();engine.submit('correct');engine.next();}assert.equal(engine.snapshot.learner.skills[skill.id],'stable');engine.continueLearning();}assert.equal(engine.snapshot.screen,'max');engine.startMax();const problem=engine.snapshot.problem!;assert.equal(master.skills.find(s=>s.id===problem.skillId)?.unitId,unit.id);engine.submission();engine.submit('correct');assert.equal(engine.snapshot.evidence.length,1);assert.equal(engine.snapshot.learner.maxUnits.includes(unit.id),false);});
}
test('TRIG: both parent MAX flags are required independently',()=>{for(const flags of [[],['TRATIO'],['QFN'],['TRATIO','QFN']]){const p=ready('TRIG');p.maxUnits=p.maxUnits.filter(id=>!['TRATIO','QFN'].includes(id)).concat(flags);for(const s of master.skills.filter(s=>['TRATIO','QFN'].includes(s.unitId)))p.skills[s.id]='stable';assert.equal(unitStatus(master,p,'TRIG'),flags.length===2?'OPEN':'LOCKED');}});
test('MAX acquisition of the last prerequisite opens TRIG on exactly the third independent success',()=>{const p=ready('QFN');p.maxUnits.push('TRATIO');startUnit(master,p,'QFN');for(let i=0;i<3;i++){const item=problems.filter(p=>p.purpose==='max'&&p.skillId==='QFN3')[i];const a:MaxAttempt={problemId:item.id,independenceKey:item.independenceKey,at:new Date(Date.parse(at)+i*86400000).toISOString(),noHint:true,noMethodSpecified:true,independent:true,examQuality:true,practicalTime:true,correctConclusion:true,readable:true,sufficientWriting:true};assert.equal(submitMax(master,p,'QFN',a),i===2);assert.equal(unitStatus(master,p,'TRIG'),i===2?'OPEN':'LOCKED');}});
test('hidden routes are absent while locked, appear when open, and cannot escape active unit',()=>{const p=createLearner(master);assert.ok(!routeMap(c,p).flatMap(g=>g.rows).some(r=>r.lane!=='MAIN'));for(const id of ['NUMTHEORY','ODE','PROBLIMIT','CPLANE']){const q=ready(id);assert.ok(routeMap(c,q).flatMap(g=>g.rows).some(r=>r.unitId===id));q.activeUnit='CAL';assert.throws(()=>startUnit(master,q,id),/Finish active/);assert.equal(routeMap(c,q).flatMap(g=>g.rows).find(r=>r.unitId===id)?.canStart,false);}});
test('optional route can be deliberately selected at a completed unit boundary; default does not force it',()=>{const e=new LearningService(true,c),cp=e.exportCheckpoint();cp.learner=ready('CPLANE');cp.screen='home';e.restoreCheckpoint(cp);e.chooseUnit('CPLANE');assert.equal(e.snapshot.learner.activeUnit,'CPLANE');const end=e.exportCheckpoint();end.current=null;end.learner.activeUnit=null;end.learner.maxUnits=[...c.mainUnitIds];end.learner.warmupRemaining=0;end.learner.lastSkillId=null;e.restoreCheckpoint(end);assert.equal(e.snapshot.task.kind,'complete');});
test('map LOCKED details contain exactly the missing parent MAX conditions',()=>{const p=ready('TRIG');p.maxUnits=p.maxUnits.filter(id=>id!=='QFN');const r=routeMap(c,p).flatMap(g=>g.rows).find(r=>r.unitId==='TRIG')!;assert.deepEqual(r.requiredMax.filter(x=>!x.acquired).map(x=>x.unitId),['QFN']);assert.equal(r.status,'LOCKED');assert.equal(r.canStart,false);});
test('three independent representatives complete MAX; repeated IDs are never recycled',()=>{const e=new LearningService(true,c),cp=e.exportCheckpoint();cp.learner=ready('TRIG');e.restoreCheckpoint(cp);e.chooseUnit('TRIG','max');assert.equal(e.snapshot.learner.skills.TRIG1,'unseen');for(let i=0;i<3;i++){e.startMax();e.submission();e.submit('correct');e.next();if(i<2)e.advanceDay();}assert.ok(e.snapshot.learner.maxUnits.includes('TRIG'));assert.equal(new Set(e.snapshot.learner.maxAttempts.TRIG.map(a=>a.independenceKey)).size,3);});
test('complete main and optional routes end-to-end without seeding MAX or stable',()=>{const e=new LearningService(true,c),cp=e.exportCheckpoint();cp.learner.diagnosticCompleted=true;cp.screen='home';e.restoreCheckpoint(cp);for(let n=0;n<master.units.length;n++){const p=e.snapshot.learner;const next=master.units.find(u=>unitStatus(master,p,u.id)==='OPEN');assert.ok(next);e.chooseUnit(next.id);for(const skill of master.skills.filter(s=>s.unitId===next.id)){assert.equal(e.snapshot.problem?.skillId,skill.id);for(let k=0;k<2;k++){e.submission();e.submit('correct');e.next();}e.continueLearning();}for(let k=0;k<3;k++){e.startMax();e.submission();e.submit('correct');e.next();if(k<2)e.advanceDay();}assert.ok(e.snapshot.learner.maxUnits.includes(next.id));}assert.equal(e.snapshot.learner.maxUnits.length,41);assert.equal(e.snapshot.task.kind,'complete');});

const mutations:[string,(x:Curriculum)=>void][]=[
 ['duplicate Unit',x=>x.master.units.push(structuredClone(x.master.units[0]))],
 ['duplicate Skill',x=>x.master.skills.push(structuredClone(x.master.skills[0]))],
 ['missing Unit',x=>x.master.units[0].prerequisites.push('UNKNOWN')],
 ['missing Skill',x=>x.master.skills[0].prerequisites.push('UNKNOWN')],
 ['unit cycle',x=>x.master.units[0].prerequisites.push('TRIG')],
 ['skill cycle',x=>x.master.skills[0].prerequisites.push('CAL3')],
 ['unit self-reference',x=>x.master.units[0].prerequisites.push(x.master.units[0].id)],
 ['skill self-reference',x=>x.master.skills[0].prerequisites.push(x.master.skills[0].id)],
 ['unit ownership',x=>x.master.skills[0].unitId='UNKNOWN'],
 ['MAX policy',x=>x.master.maxDefinitions[0].requiredSuccesses=2],
 ['CrossSkill',x=>x.master.skills[0].crossSkillIds.push('X99')],
 ['optional unlocks main',x=>{x.master.units.find(u=>u.id==='REP')!.prerequisites.push('CPLANE');x.units.find(u=>u.unitId==='REP')!.requiredMax.push('CPLANE');}],
 ['mandatory parent omitted from both DAG and guide',x=>{x.master.units.find(u=>u.id==='TRIG')!.prerequisites=['TRATIO'];x.units.find(u=>u.unitId==='TRIG')!.requiredMax=['TRATIO'];}],
 ['MAX template writing missing',x=>x.units[0].max.writing=false],
 ['problem reference',x=>x.problems[0].skillId='UNKNOWN'],
 ['problem duplicate',x=>x.problems.push(structuredClone(x.problems[0]))],
 ['skill outside unit route',x=>x.master.skills[0].prerequisites.push('CPLANE1')],
 ['guide cross reference',x=>x.skills[0].crossSkillIds.push('X99')]
];
for(const [name,change] of mutations)test('validator rejects '+name,()=>{const x=structuredClone(c);change(x);assert.throws(()=>validateCurriculum(x));});
async function oldSaved(profile:'repair'|'max-two'|'complete'|'new'='repair'){const repo=new MemoryLearningRepository(),clock=new ManualClock(at),app=new LearningApplication(repo,clock,true);await app.boot();await app.useDemo(profile);return {repo,clock,app,doc:decodeDocument(await repo.load(app.namespace),app.namespace)};}
for(const profile of ['repair','max-two','complete','new'] as const)test(`migration preserves ${profile} checkpoint, histories and IDs and adds unseen skills only`,async()=>{const {doc}=await oldSaved(profile),before=structuredClone(doc),next=migrateDocument(doc,doc.namespace,c,at);assert.deepEqual(doc,before);assert.deepEqual(next.migration?.previousCheckpoint,doc.checkpoint);const oldSkills=Object.keys(doc.checkpoint.learner.skills);for(const id of oldSkills)assert.equal(next.checkpoint.learner.skills[id],doc.checkpoint.learner.skills[id]);for(const id of Object.keys(next.checkpoint.learner.skills).filter(id=>!oldSkills.includes(id)))assert.equal(next.checkpoint.learner.skills[id],'unseen');const restored=structuredClone(next.checkpoint);restored.learner.skills=doc.checkpoint.learner.skills;assert.deepEqual(restored,doc.checkpoint);assert.deepEqual(next.repairs,doc.repairs);assert.deepEqual(next.sessions,doc.sessions);assert.deepEqual(next.expEvents,doc.expEvents);assert.deepEqual(migrateDocument(next,next.namespace,c,at),next);});
test('failed migration write preserves original repository and is retryable',async()=>{const {repo,clock,doc}=await oldSaved();repo.failNext=true;const app=new LearningApplication(repo,clock,true,c);await assert.rejects(()=>app.boot(),/保存/);assert.deepEqual(await repo.load(doc.namespace),doc);await app.boot();assert.equal(app.service.snapshot.learner.activeUnit,'QFN');assert.equal(Object.keys(app.service.snapshot.learner.skills).length,123);});
test('migrated interrupted repair returns to exact original problem after two successes',async()=>{const {repo,clock,doc}=await oldSaved();const expected=doc.checkpoint.learner.repair!,a=new LearningApplication(repo,clock,true,c);await a.boot();await a.execute(()=>a.service.continueLearning());for(let i=0;i<2;i++){await a.execute(()=>{a.service.submission();a.service.submit('correct');});await a.execute(()=>a.service.next());}assert.equal(a.service.snapshot.problem?.id,expected.returnToProblemId);assert.equal(a.service.snapshot.learner.activeUnit,'QFN');const reopened=new LearningApplication(repo,clock,true,c);await reopened.boot();assert.equal(reopened.service.snapshot.problem?.id,expected.returnToProblemId);});
test('unknown future curriculum and corrupt old data are never overwritten by migration',async()=>{for(const kind of ['version','corrupt']){const {repo,clock,doc}=await oldSaved();if(kind==='version')doc.curriculumVersion='future';else doc.checkpoint.used.push('MISSING');repo.records.set(doc.namespace,doc);const a=new LearningApplication(repo,clock,true,c);await assert.rejects(()=>a.boot());assert.deepEqual(await repo.load(doc.namespace),doc);}});
test('fresh full-curriculum persistence works without any migration',async()=>{const repo=new MemoryLearningRepository(),a=new LearningApplication(repo,new ManualClock(at),false,c);await a.boot();await a.execute(()=>a.service.continueLearning());const d=decodeDocument(await repo.load(a.namespace),a.namespace,c);assert.equal(d.migration,undefined);assert.equal(Object.keys(d.checkpoint.learner.skills).length,123);});
