import {explanationGraph} from './explanation-graph.ts';
import type {ExplanationGraph,Polynomial} from './explanation-graph.ts';
export interface DynamicBoundary {value:number;label:string}
export interface DynamicSpec {parameter:'a'|'k';min:number;max:number;initial:number;boundaries:DynamicBoundary[];regions:string[];region:(v:number)=>number;graph:(v:number)=>ExplanationGraph;comparisonGraph?:(v:number)=>ExplanationGraph;reason:(v:number)=>string;}
const round=(v:number)=>String(Math.round(v*100)/100);
const boundary=(value:number,label=String(value)):DynamicBoundary=>({value,label});
const sameValue=(a:number,b:number)=>Math.abs(a-b)<=1e-10*Math.max(1,Math.abs(a),Math.abs(b));
function graph(title:string,curves:Polynomial[],formulas:string[],view:ExplanationGraph['view'],caption:string,domain?:[number,number]):ExplanationGraph{return {title,curves:curves.map((coefficients,i)=>({coefficients,formula:formulas[i]})),view,caption,domain};}
const axisRegion=(v:number,l:number,r:number)=>v<l?0:v<=r?1:2;
const axisReason=(v:number,l:number,r:number)=>v<l?'軸は指定区間の左側です。区間内で軸に最も近い点は左端です。':v>r?'軸は指定区間の右側です。区間内で軸に最も近い点は右端です。':`軸は指定区間内${v===l||v===r?'（端点と一致）':''}です。頂点を候補にできます。`;
export const dynamicSpecs:Record<string,DynamicSpec>={
 'QF-PARAM-V1-1':{parameter:'a',min:-2,max:4,initial:1,boundaries:[boundary(0),boundary(2)],regions:['a<0','0≦a≦2','a>2'],region:v=>axisRegion(v,0,2),reason:v=>axisReason(v,0,2)+' 最小になる点が変わるため、境界0,2で場合分けします。',graph:a=>graph(`軸 x=${round(a)}`,[[1,-2*a,a*a]],['y=(x−a)²'],[-3,5,-2,38],'太線の中で軸に最も近い点を探します。',[0,2])},
 'QF-PARAM-V1-2':{parameter:'a',min:-2,max:4,initial:1,boundaries:[boundary(1)],regions:['a<1','a=1','a>1'],region:v=>v<1?0:sameValue(v,1)?1:2,reason:a=>`f(2)−f(0)=${round(4-4*a)}。${a<1?'右端x=2':a>1?'左端x=0':'両端x=0,2'}で最大になります。最大の境界は軸が端点を通る0,2ではなく、両端の高さが等しくなる1です。`,graph:a=>graph(`端点の高さを比較（a=${round(a)}）`,[[1,-2*a,a*a]],['y=(x−a)²'],[-3,5,-2,38],'軸から遠い端点ほど高さが大きくなります。',[0,2])},
 'QF-PARAM-V1-3':{parameter:'a',min:-1,max:2,initial:0,boundaries:[boundary(0),boundary(1)],regions:['a<0','a=0','0<a<1','a=1','a>1'],region:a=>a<0?0:sameValue(a,0)?1:a<1?2:sameValue(a,1)?3:4,reason:a=>`D=4a(a−1)=${round(4*a*(a-1))}。${sameValue(a,0)||sameValue(a,1)?'共有点は1点で、二つのグラフが接します。':a<0||a>1?'共有点は2点です。':'共有点はありません。'} 接するa=0,1を境に共有点の個数が変わります。`,graph:a=>graph(`共有点の変化（a=${round(a)}）`,[[1,0,0],[0,2*a,-a]],['y=x²','y=2ax−a'],[-2,5,-4,18],'同じxで高さが等しい点が共有点です。差x²−2ax+aの実数解の個数と対応します。')},
 'QF-PARAM-V1-4':{parameter:'a',min:-3,max:3,initial:0,boundaries:[boundary(-1,'−1'),boundary(1)],regions:['a<−1','−1≦a≦1','a>1'],region:a=>axisRegion(a,-1,1),reason:a=>axisReason(a,-1,1)+' 下に開くので、軸に最も近い区間内の点で最大になります。',graph:a=>graph(`下に開く放物線（a=${round(a)}）`,[[-1,2*a,2-a*a]],['y=−(x−a)²+2'],[-4,4,-16,4],'軸が端点を通るa=−1,1で、最大になる点の選び方が変わります。',[-1,1])},
 'QF-SIGN-V1-2':{parameter:'a',min:0,max:4,initial:2,boundaries:[boundary(2)],regions:['a<2','a=2','a>2'],region:a=>a<2?0:sameValue(a,2)?1:2,reason:a=>sameValue(a,2)?'[a,a+1]=[2,3]となり、区間全体で0以下です。':'指定区間の'+(a<2?'左端が2より左':'右端が3より右')+'に出ています。0以下となる[2,3]に区間全体を含めるには、a=2が必要です。',graph:a=>graph(`動く区間 [${round(a)}, ${round(a+1)}]`,[[1,-5,6]],['y=x²−5x+6'],[-1,6,-2,9],'放物線は固定です。動くのは青い帯で示した区間[a,a+1]です。',[a,a+1])},
 'QF-SIGN-V1-3':{parameter:'k',min:-2,max:4,initial:0,boundaries:[boundary(-1,'−1'),boundary(3)],regions:['k<−1','k=−1','−1<k<3','k=3','k>3'],region:k=>k< -1?0:sameValue(k,-1)?1:k<3?2:sameValue(k,3)?3:4,reason:k=>k< -1?'共有点はありません。':sameValue(k,-1)?'頂点で接する1点だけなので、「異なる2点」を満たしません。':k<3?'共有点は異なる2点で、両方とも0≦x≦4の内側にあります。':sameValue(k,3)?'共有点のx座標は両端0,4です。端点を含むため、この境界は条件を満たします。':'共有点は2点ありますが、両方とも指定区間の外です。D>0だけでは区間条件を判断できません。',graph:k=>graph(`水平線の移動（k=${round(k)}）`,[[1,-4,3],[0,0,k]],['y=x²−4x+3','y=k'],[-1,5,-3,8],'k=−1は接する境界、k=3は共有点が指定区間の端に達する境界です。',[0,4])}
};
function numberLine(s:DynamicSpec,v:number,currentLabel:string){
 const x=(a:number)=>25+270*(a-s.min)/(s.max-s.min),cuts=[s.min,...s.boundaries.map(b=>b.value),s.max];
 return `<svg class="parameter-line" viewBox="0 0 320 88" role="img" aria-label="${s.parameter}=${currentLabel}。現在の範囲：${s.regions[s.region(v)]}"><path d="M20,40H300" stroke="#435c6f" stroke-width="2"/>${cuts.slice(0,-1).map((l,i)=>{const r=cuts[i+1];return `<path d="M${x(l)},40H${x(r)}" stroke="${v>l&&v<r?'#136d9c':'#becbd5'}" stroke-width="7"/>`;}).join('')}${s.boundaries.map(b=>`<circle cx="${x(b.value)}" cy="40" r="5" fill="${sameValue(v,b.value)?'#136d9c':'white'}" stroke="#136d9c"/><text x="${x(b.value)}" y="66" text-anchor="middle">${s.parameter}=${b.label}</text>`).join('')}<path d="M${x(v)-6},17L${x(v)},29L${x(v)+6},17Z" fill="#aa471f"/><text x="${x(v)}" y="12" text-anchor="middle">${currentLabel}</text><text x="25" y="85">${s.min}</text><text x="295" y="85" text-anchor="end">${s.max}</text></svg><div class="parameter-regions">${s.regions.map((r,i)=>`<span ${i===s.region(v)?'aria-current="true" class="current"':''}>${r}</span>`).join('')}</div><p class="muted">矢印が現在値、丸が場合分けの境界です。数直線の表示範囲はスライダーの範囲です。</p>`;
}
function body(s:DynamicSpec,v:number,currentLabel=round(v)){return `${explanationGraph(s.graph(v))}${s.comparisonGraph?explanationGraph(s.comparisonGraph(v)):""}<h3>場合分けと現在の位置</h3>${numberLine(s,v,currentLabel)}<p class="notice" aria-live="polite">${s.reason(v)}</p>`;}
export function boundaryJump(s:DynamicSpec,index:number){const target=s.boundaries[index];if(!target)throw new Error('Unknown dynamic boundary');return {value:target.value,label:target.label,rangeValue:String(target.value),region:s.region(target.value),reason:s.reason(target.value)};}
export function dynamicQuadratic(id:string,s:DynamicSpec|undefined=dynamicSpecs[id]){if(!s)return '';const initialLabel=s.boundaries.find(b=>sameValue(b.value,s.initial))?.label??round(s.initial);return `<section class="dynamic-quadratic" data-dynamic="${id}"><label>パラメータ ${s.parameter} = <output>${initialLabel}</output><input type="range" min="${s.min}" max="${s.max}" step="0.05" value="${s.initial}" aria-label="パラメータ ${s.parameter}"/></label><div class="boundary-buttons">${s.boundaries.map((v,index)=>`<button type="button" class="small" data-boundary-index="${index}" title="exact: ${v.value}">境界 ${s.parameter}=${v.label}</button>`).join('')}</div><div data-dynamic-body>${body(s,s.initial,initialLabel)}</div></section>`;}
export function bindDynamicQuadratic(root:HTMLElement,specs:Record<string,DynamicSpec>=dynamicSpecs){for(const host of root.querySelectorAll<HTMLElement>('[data-dynamic]')){
 const s=specs[host.dataset.dynamic!];if(!s)continue;const input=host.querySelector<HTMLInputElement>('input')!;
 let currentValue=s.initial;
 const update=(label=round(currentValue))=>{host.querySelector('output')!.textContent=label;host.querySelector('[data-dynamic-body]')!.innerHTML=body(s,currentValue,label);};
 input.addEventListener('input',()=>{currentValue=Number(input.value);update();});
 for(const b of host.querySelectorAll<HTMLButtonElement>('[data-boundary-index]'))b.addEventListener('click',()=>{const target=boundaryJump(s,Number(b.dataset.boundaryIndex));currentValue=target.value;input.value=target.rangeValue;update(target.label);});
}}
