import {integratedProblems} from '../prototype/quadratic-integrated-family.ts';
import type {IntegratedQuadraticProblem} from '../prototype/quadratic-integrated-family.ts';
import {dynamicQuadratic,bindDynamicQuadratic} from './dynamic-quadratic.ts';
import type {DynamicSpec} from './dynamic-quadratic.ts';
import {explanationGraph} from './explanation-graph.ts';
import {answerText} from '../prototype/integrated-quadratic-math.ts';
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const lines=(s:string)=>esc(s).replaceAll('\n','<br>');
const json=(v:unknown)=>esc(JSON.stringify(v,null,2));
export function integratedDynamicSpec(p:IntegratedQuadraticProblem):DynamicSpec{
 const boundaries=p.boundaries,values=boundaries.map(b=>b.value),labels=boundaries.map(b=>b.label),min=Math.floor(Math.min(p.initial,values[0]??0)-2),max=Math.ceil(Math.max(p.initial,values.at(-1)??0)+2);
 const regions=values.length?[`k＜${labels[0]}`,...labels.flatMap((v,i)=>[`k=${v}`,...(i<labels.length-1?[`${v}＜k＜${labels[i+1]}`]:[])]),`k＞${labels.at(-1)}`]:['すべての実数k'];
 return {parameter:'k',min,max,initial:p.initial,boundaries,regions,region:k=>{for(let i=0;i<values.length;i++){if(Math.abs(k-values[i])<1e-9)return i*2+1;if(k<values[i])return i*2;}return values.length*2;},graph:k=>p.graphs(k)[0],...(p.graphs(p.initial).length>1?{comparisonGraph:(k:number)=>p.graphs(k)[1]}:{}),reason:k=>{const o=p.oracle(k);return p.answer.kind==='cases'?'現在のkで頂点と両端の値を確認し、上の該当する場合の式と比べてください。':`現在のkは元の条件を${o.satisfied?'満たします':'満たしません'}。境界そのものと、その左右の変化を確認してください。`;}};
}
let current=0,phase:'problem'|'choices'|'result'='problem',selected='',notice='';let ordered:IntegratedQuadraticProblem['choices']=[];
export function resetIntegratedProblem(id:string){const i=integratedProblems.findIndex(p=>p.id===id);if(i<0)return;current=i;phase='problem';selected='';notice='';}
export function renderIntegratedResult(p:IntegratedQuadraticProblem,id:string){const c=p.choices.find(c=>c.choiceId===id),graphs=p.graphs(p.initial);
 return `<h2>${c?.correct?'最終結論は正しいです':'最終結論は未解決です'}</h2><p>紙の途中式は評価していません。1回の選択で弱点を確定しません。</p><section class="explanation quadratic-answer"><h2>考え方</h2><p>${esc(p.explanation.thinking)}</p><h2>解き方</h2>${p.explanation.steps.map(s=>`<p>${lines(s)}</p>`).join('')}<h2>グラフで確かめる</h2>${graphs.length?p.dynamic?dynamicQuadratic(p.id,integratedDynamicSpec(p)):graphs.map(explanationGraph).join(''):'<p>この問題では、根の和と配置条件を上の式で確認します。補助グラフは付けていません。</p>'}<h2>答え</h2><p class="answer-example">${lines(p.explanation.answer)}</p></section><details class="panel"><summary>検証情報：導出・モデル・必要能力・弱点仮説</summary><h3>structure signature</h3><p>${p.structureSignature.join(' + ')}</p><h3>solution trace</h3>${p.solutionTrace.map(s=>`<details><summary>${s.kind}</summary><p>${lines(s.explanation)}</p><pre>${json(s.result)}</pre></details>`).join('')}<h3>使用した数学モデル</h3><pre>${json(p.models)}</pre><h3>独立oracle・元条件検証</h3><p>k=<output data-integrated-oracle-value>${p.boundaries.find(b=>Math.abs(b.value-p.initial)<1e-9)?.label??p.initial}</output>の直接評価。動的グラフの操作と連動します。</p><pre data-integrated-oracle>${json(p.oracle(p.initial))}</pre><h3>この問題で必要な能力</h3><ul>${p.problemRequirements.map(r=>`<li>${esc(r.description)}（${r.crossSkills.join('、')}）</li>`).join('')}</ul><h3>今回選択した誤答の弱点仮説</h3>${c?.mistakeHypotheses.map(h=>`<p>${esc(h.description)}。CrossSkill：${h.crossSkills.join('、')}。弱点候補：${h.weaknessTags.join('、')}</p>`).join('')||'<p>なし</p>'}<h3>採用・除外誤答</h3>${p.decisions.map(d=>`<details><summary>${d.selected?'採用':'除外'}：${esc(d.type)}</summary><p>${lines(answerText(d.answer))}</p><p>diagnosticScore：${d.diagnosticScore}</p><p>${esc(d.reason)}</p><p>${esc(d.selectionReason)}</p><pre>${json(d.errorModel)}</pre></details>`).join('')}</details>`;
}
export function renderIntegratedPrototype(){const p=integratedProblems[current],body=phase==='problem'?'<p>紙に方針・途中式・条件・結論を書いてから進んでください。</p><button class="primary" data-integrated-action="choices">紙に解いたので4択へ</button>':phase==='choices'?`<fieldset class="answer-options"><legend>紙答案の最終結果を選ぶ</legend>${ordered.map(c=>`<label><input type="radio" name="integrated-choice" value="${c.choiceId}"/><span>${lines(c.text)}</span></label>`).join('')}</fieldset><button class="primary" data-integrated-action="submit">最終結論を提出する</button>`:renderIntegratedResult(p,selected);
 return `<div class="family-prototype integrated-prototype"><h1>生成問題ファミリー試作5 二次関数・総合判断</h1><p class="notice">検証専用の12題です。通常学習・stable・MAXには反映しません。まだreviewed教材ではありません。</p><label for="integrated-number">確認する問題</label><select id="integrated-number">${integratedProblems.map(q=>`<option value="${q.id}" ${q.id===p.id?'selected':''}>${q.index}. ${q.level}</option>`).join('')}</select><section class="problem-paper"><p class="paper-caption">問題 ${p.index} / 12 ・ ${p.level}</p><p class="math-text">${esc(p.prompt)}</p></section><p role="status">${esc(notice)}</p>${body}<button class="secondary" data-integrated-action="restart">この問題を最初から見る</button><button class="secondary" data-integrated-action="next">次の問題へ</button><button class="secondary" data-integrated-action="close">通常の検証画面へ戻る</button></div>`;
}
export function integratedAttempt(p:IntegratedQuadraticProblem,id:string,at:string){const c=p.choices.find(c=>c.choiceId===id);if(!c)throw new Error('Unknown integrated choice');return {problemId:p.id,choiceId:id,correct:c.correct,structureSignature:p.structureSignature,problemRequirements:p.problemRequirements,mistakeHypotheses:c.mistakeHypotheses,hypothesisOnly:true,at,generatorVersion:1};}
export function bindIntegratedPrototype(root:HTMLElement,render:()=>void,close:()=>void){const p=integratedProblems[current];if(p.dynamic&&p.graphs(p.initial).length){bindDynamicQuadratic(root,{[p.id]:integratedDynamicSpec(p)});
  const updateOracle=(k:number,label:string)=>{const output=root.querySelector('[data-integrated-oracle]'),value=root.querySelector('[data-integrated-oracle-value]');if(output)output.textContent=JSON.stringify(p.oracle(k),null,2);if(value)value.textContent=label;};
  root.querySelector<HTMLInputElement>('[data-dynamic] input')?.addEventListener('input',e=>{const k=Number((e.target as HTMLInputElement).value);updateOracle(k,String(Math.round(k*1000)/1000));});
  for(const b of root.querySelectorAll<HTMLButtonElement>('[data-boundary-index]'))b.addEventListener('click',()=>{const value=p.boundaries[Number(b.dataset.boundaryIndex)];updateOracle(value.value,value.label);});
 }
 root.querySelector<HTMLSelectElement>('#integrated-number')?.addEventListener('change',e=>{resetIntegratedProblem((e.target as HTMLSelectElement).value);render();});
 for(const button of root.querySelectorAll<HTMLButtonElement>('[data-integrated-action]'))button.addEventListener('click',()=>{
  const action=button.dataset.integratedAction;if(action==='close'){close();return;}if(action==='restart')resetIntegratedProblem(p.id);if(action==='next')resetIntegratedProblem(integratedProblems[(current+1)%integratedProblems.length].id);
  if(action==='choices'){ordered=[...p.choices];for(let i=ordered.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[ordered[i],ordered[j]]=[ordered[j],ordered[i]];}phase='choices';}
  if(action==='submit'){const id=root.querySelector<HTMLInputElement>('input[name="integrated-choice"]:checked')?.value;if(!id){notice='紙答案に当てはまる結論を選んでください。';render();return;}const record=integratedAttempt(p,id,new Date().toISOString());selected=id;phase='result';try{const key='math-integrated-family-prototype:attempts:v1',saved=JSON.parse(localStorage.getItem(key)??'[]');if(!Array.isArray(saved))throw new Error('Invalid history');saved.push(record);localStorage.setItem(key,JSON.stringify(saved));notice='第5ファミリー専用の履歴に記録しました。';}catch{notice='試作履歴を保存できませんでした。結果はこの画面で確認できます。';}}
  render();root.querySelector('.family-prototype')?.scrollIntoView({block:'start'});
 });
}
