import {placementProblems,placementGraphState,polynomialText,setText,targetText} from '../prototype/quadratic-placement-family.ts';
import type {PlacementProblem} from '../prototype/quadratic-placement-family.ts';
import {dynamicQuadratic,bindDynamicQuadratic} from './dynamic-quadratic.ts';
import type {DynamicSpec} from './dynamic-quadratic.ts';
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const decimal=(v:number)=>String(Math.round(v*10000)/10000);
export function placementDynamicSpec(p:PlacementProblem):DynamicSpec{
 const boundaries=p.model.boundaries,values=boundaries.map(b=>b.value),labels=boundaries.map(b=>b.label),min=Math.floor((values[0]??0)-2),max=Math.ceil((values.at(-1)??0)+2);
 const regions=labels.length?[`k＜${labels[0]}`,...labels.flatMap((v,i)=>[`k=${v}`,...(i<labels.length-1?[`${v}＜k＜${labels[i+1]}`]:[])]),`k＞${labels.at(-1)}`]:['すべての実数k'];
 const first=p.model.answer[0],initial=first?first.lo===null?(first.hi?.value??0)-1:first.hi===null?first.lo.value+1:(first.lo.value+first.hi.value)/2:0;
 return {parameter:'k',min,max,initial,boundaries,regions,region:k=>{for(let i=0;i<values.length;i++){if(Math.abs(k-values[i])<1e-9)return i*2+1;if(k<values[i])return i*2;}return values.length*2;},graph:k=>placementGraphState(p.model.parameters,k).graph,reason:k=>{const s=placementGraphState(p.model.parameters,k);return `D≈${decimal(s.D)}、軸h≈${decimal(s.h)}。${s.endpointValues.map(p=>`qₖ(${p.x})≈${decimal(p.value)}`).join('、')}。root-placement oracle：${s.roots.length?`α≈${decimal(s.roots[0])}、β≈${decimal(s.roots[1])}`:'異なる2実根なし'}。現在の根配置は目標を${s.satisfied?'満たします':'満たしません'}。`;}};
}
let current=0,phase:'problem'|'choices'|'result'='problem',selected='',notice='';let ordered:PlacementProblem['choices']=[];
export function resetPlacementProblem(id:string){const i=placementProblems.findIndex(p=>p.id===id);if(i<0)return;current=i;phase='problem';selected='';notice='';}
export function renderPlacementResult(p:PlacementProblem,id:string){const c=p.choices.find(c=>c.choiceId===id),m=p.model;
 return `<h2>${c?.correct?'最終結論は正しいです':'最終結論は未解決です'}</h2><p>紙の途中式は評価していません。1回の選択で弱点を確定しません。</p><section class="explanation quadratic-answer"><h2>考え方</h2><p>${esc(p.explanation.thinking)}</p><h2>解き方</h2>${p.explanation.steps.map(s=>`<p>${esc(s)}</p>`).join('')}<h2>グラフで確かめる</h2>${dynamicQuadratic(p.id,placementDynamicSpec(p))}<h2>答え</h2><p class="answer-example">${esc(p.explanation.answer)}</p></section><details class="panel"><summary>検証情報：数学モデル・必要能力・弱点仮説・誤答選定</summary><h3>数学モデル</h3><p>A=${m.A}、B=${esc(polynomialText(m.B))}、C=${esc(polynomialText(m.C))}</p><p>D=${esc(polynomialText(m.D))}、h=${esc(polynomialText(m.axis))}</p><p>${m.pointValues.map(v=>`qₖ(${v.x})=${esc(polynomialText(v.polynomial))}`).join('、')}</p><p>α=${esc(m.rootFormula.alpha)}、β=${esc(m.rootFormula.beta)}（D>0、sgn(A)はAの符号）</p><p>目標：${esc(targetText(m.parameters.target))}</p><h3>必要条件と各条件のkの集合</h3>${m.conditions.map(c=>`<p>${esc(c.label)} ⇔ ${esc(polynomialText(c.polynomial))}${c.inclusive?'≧':'&gt;'}0：${esc(setText(c.set))}</p>`).join('')}<p>最終的な共通部分：${esc(setText(m.answer))}</p><p>境界：${m.boundaries.map(b=>`${esc(b.label)}（内部値 ${b.value}）`).join('、')}</p><p>実根を元条件へ直接代入したoracleの現在の結果は、スライダーに連動してグラフの下に表示します。</p><h3>この問題で必要な能力</h3><ul>${p.problemRequirements.map(r=>`<li>${esc(r.description)}（${r.crossSkills.join('、')}）</li>`).join('')}</ul><h3>今回選択した誤答の弱点仮説</h3>${c?.mistakeHypotheses.map(h=>`<p>${esc(h.description)}。タグ：${h.weaknessTags.join('、')}／CrossSkill：${h.crossSkills.join('、')}</p>`).join('')||'<p>なし</p>'}<h3>4択と誤答候補</h3><p>正答：${esc(p.explanation.answer)}</p>${p.decisions.map(d=>`<section><h4>${d.selected?'採用':'除外'}：${d.type}${d.choice.choiceId===id?'（今回選択）':''}</h4><p>${esc(d.choice.text)}</p><p>diagnosticScore：${d.diagnosticScore}</p><p>${esc(d.reason)}</p><p>採用／除外理由：${esc(d.selectionReason)}</p><p>誤答モデル（${d.errorModel.operation==='union'?'和集合':'共通部分'}）：${d.errorModel.conditions.map(c=>`${esc(polynomialText(c.polynomial))}${c.inclusive?'≧':'&gt;'}0`).join(' ／ ')}</p></section>`).join('')}</details>`;
}
export function renderPlacementPrototype(){const p=placementProblems[current];const body=phase==='problem'?'<p>紙に途中式・条件・結論を書いてから進んでください。</p><button class="primary" data-placement-action="choices">紙に解いたので4択へ</button>':phase==='choices'?`<fieldset class="answer-options"><legend>紙答案の最終結果を選ぶ</legend>${ordered.map(c=>`<label><input type="radio" name="placement-choice" value="${c.choiceId}"/><span>${esc(c.text)}</span></label>`).join('')}</fieldset><button class="primary" data-placement-action="submit">最終結論を提出する</button>`:renderPlacementResult(p,selected);
 return `<div class="family-prototype"><h1>生成問題ファミリー試作4 2解の位置・区間条件</h1><p class="notice">検証専用の12題です。通常学習・stable・MAXには反映しません。まだreviewed教材ではありません。</p><label for="placement-number">確認する問題</label><select id="placement-number">${placementProblems.map(q=>`<option value="${q.id}" ${q.id===p.id?'selected':''}>${q.index}. ${q.model.parameters.level}／${esc(targetText(q.model.parameters.target))}</option>`).join('')}</select><section class="problem-paper"><p class="paper-caption">問題 ${p.index} / 12 ・ ${p.model.parameters.level}</p><p class="math-text">${esc(p.prompt)}</p></section><p role="status">${esc(notice)}</p>${body}<button class="secondary" data-placement-action="restart">この問題を最初から見る</button><button class="secondary" data-placement-action="next">次の問題へ</button><button class="secondary" data-placement-action="close">通常の検証画面へ戻る</button></div>`;
}
export function placementAttempt(p:PlacementProblem,id:string,at:string){const c=p.choices.find(c=>c.choiceId===id);if(!c)throw new Error('Unknown placement choice');return {problemId:p.id,parameters:p.model.parameters,choiceId:id,correct:c.correct,problemRequirements:p.problemRequirements,mistakeHypotheses:c.mistakeHypotheses,hypothesisOnly:true,at,generatorVersion:1};}
export function bindPlacementPrototype(root:HTMLElement,render:()=>void,close:()=>void){const p=placementProblems[current];bindDynamicQuadratic(root,{[p.id]:placementDynamicSpec(p)});
 root.querySelector<HTMLSelectElement>('#placement-number')?.addEventListener('change',e=>{resetPlacementProblem((e.target as HTMLSelectElement).value);render();});
 for(const button of root.querySelectorAll<HTMLButtonElement>('[data-placement-action]'))button.addEventListener('click',()=>{
  const action=button.dataset.placementAction;if(action==='close'){close();return;}
  if(action==='restart')resetPlacementProblem(p.id);if(action==='next')resetPlacementProblem(placementProblems[(current+1)%placementProblems.length].id);
  if(action==='choices'){ordered=[...p.choices];for(let i=ordered.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[ordered[i],ordered[j]]=[ordered[j],ordered[i]];}phase='choices';}
  if(action==='submit'){const id=root.querySelector<HTMLInputElement>('input[name="placement-choice"]:checked')?.value;if(!id){notice='紙答案に当てはまる結論を選んでください。';render();return;}const record=placementAttempt(p,id,new Date().toISOString());selected=id;phase='result';try{const key='math-placement-family-prototype:attempts:v1',saved=JSON.parse(localStorage.getItem(key)??'[]');if(!Array.isArray(saved))throw new Error('Invalid history');saved.push(record);localStorage.setItem(key,JSON.stringify(saved));notice='第4ファミリー専用の履歴に記録しました。';}catch{notice='試作履歴を保存できませんでした。結果はこの画面で確認できます。';}}
  render();root.querySelector('.family-prototype')?.scrollIntoView({block:'start'});
 });
}
