import {bankRecords,bankArtifact,bankCurriculum} from '../bank/catalog.ts';
import type {BankRecord} from '../bank/types.ts';
import {bankGraphs} from '../bank/graphs.ts';
import {explanationGraph} from './explanation-graph.ts';
import {dynamicQuadratic,bindDynamicQuadratic} from './dynamic-quadratic.ts';
import type {DynamicSpec} from './dynamic-quadratic.ts';
import {countGraphState} from '../prototype/quadratic-count-family.ts';
const esc=(v:unknown)=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const lines=(v:string)=>esc(v).replaceAll('\n','<br>');
const json=(v:unknown)=>`<pre class="bank-json">${esc(JSON.stringify(v,null,2))}</pre>`;
export function bankDynamicSpec(p:BankRecord):DynamicSpec|undefined{
 const spec=p.graphSpec;if(!spec?.dynamic)return;
 const {boundaries,initial,parameter}=spec,values=boundaries.map(b=>b.value),labels=boundaries.map(b=>b.label);
 const regions=values.length?[`${parameter}＜${labels[0]}`,...labels.flatMap((v,i)=>[`${parameter}=${v}`,...(i<labels.length-1?[`${v}＜${parameter}＜${labels[i+1]}`]:[])]),`${parameter}＞${labels.at(-1)}`]:['すべての実数'];
 return {parameter,min:Math.floor(Math.min(initial,...values)-2),max:Math.ceil(Math.max(initial,...values)+2),initial,boundaries,regions,region:v=>{for(let i=0;i<values.length;i++){if(Math.abs(v-values[i])<1e-9)return i*2+1;if(v<values[i])return i*2;}return values.length*2;},graph:v=>bankGraphs(spec,v)[0],...(bankGraphs(spec,initial).length>1?{comparisonGraph:(v:number)=>bankGraphs(spec,v)[1]}:{}),reason:v=>spec.model.kind==='count'?`D≈${Number(countGraphState(spec.model.parameters,v).D.toPrecision(5))}、共有点は${countGraphState(spec.model.parameters,v).count}個です。境界とその両側を比べてください。`:'現在の値で、図と上の解説の条件を照合してください。境界そのものと、その左右を比べると、場合分けの意味が分かります。'};
}
export function bankExplanation(p:BankRecord){const spec=bankDynamicSpec(p);return `<section class="explanation quadratic-answer"><h2>考え方</h2><p>${lines(p.explanation.thinking)}</p><h2>解き方</h2>${p.explanation.steps.map(s=>`<p>${lines(s)}</p>`).join('')}${p.graphSpec?`<h2>グラフで確かめる</h2>${spec?dynamicQuadratic(p.id,spec):bankGraphs(p.graphSpec,p.graphSpec.initial).map(explanationGraph).join('')}`:''}<h2>答え</h2><p class="answer-example">${lines(p.answer)}</p></section>`;}
export function bankDetails(p:BankRecord,choiceId?:string){return `<details class="panel"><summary>バンク検証情報：能力・仮説・validator・oracle</summary><p>${esc(p.familyId)} / ${esc(p.variantId)} / STEP ${p.step} / ${p.difficultyTier}</p><h3>構造</h3><p>${esc(p.structureSignature)}</p><h3>この問題で必要な能力</h3>${json(p.problemRequirements)}<h3>選択した誤答と整合する弱点仮説</h3><p>1回の選択で弱点を確定しません。</p>${json(p.choices.find(c=>c.choiceId===choiceId)?.mistakeHypotheses??[])}<h3>4択・正答・誤答仮説</h3>${json(p.choices)}<h3>validator / 独立oracle</h3>${json(p.validation)}<h3>パラメータ・導出</h3>${json(p.parameters)}${p.solutionTrace?json(p.solutionTrace):''}</details>`;}
export function bindBankGraph(root:HTMLElement,p:BankRecord){const spec=bankDynamicSpec(p);if(spec)bindDynamicQuadratic(root,{[p.id]:spec});}
let family='',step='',tier='',selected=bankRecords[0].id;
const count=(key:'familyId'|'step'|'difficultyTier')=>[...new Set(bankRecords.map(p=>String(p[key])))].map(name=>`${name}: ${bankRecords.filter(p=>String(p[key])===name).length}`).join(' ／ ');
export function renderBank(){const eligible=bankRecords.filter(p=>(!family||p.familyId===family)&&(!step||String(p.step)===step)&&(!tier||p.difficultyTier===tier));if(!eligible.some(p=>p.id===selected))selected=eligible[0]?.id??'';const p=eligible.find(p=>p.id===selected),reviewed=bankCurriculum.problems.filter(p=>p.reviewStatus==='reviewed'),qfn=reviewed.filter(p=>bankCurriculum.master.skills.find(s=>s.id===p.skillId)?.unitId==='QFN');
 const filter=(id:string,label:string,values:string[],value:string)=>`<label>${label}<select data-bank-filter="${id}"><option value="">すべて</option>${values.map(v=>`<option ${v===value?'selected':''}>${v}</option>`).join('')}</select></label>`;
 return `<section class="bank-review"><h1>二次関数 本番問題バンク</h1><p>QFN総数 ${qfn.length+bankRecords.length}（固定reviewed ${qfn.filter(p=>p.purpose==='practice').length}、固定MAX ${qfn.filter(p=>p.purpose==='max').length}、verified-generated ${bankRecords.length}）。修復用reviewed ${reviewed.length-qfn.length}題は別枠。</p><p>生成問題 family別：${count('familyId')}</p><p>STEP別：${count('step')}</p><p>難易度別：${count('difficultyTier')}</p><p>構造 ${new Set(bankRecords.map(p=>p.structureSignature)).size}種類。同一family・構造は最大${bankArtifact.audit.signatureMaximum}題。</p><p>下の操作は教材確認用のデモに切り替わり、通常学習データには反映しません。</p>${filter('family','ファミリー',[...new Set(bankRecords.map(p=>p.familyId))],family)}${filter('step','STEP',['2','3','4','5'],step)}${filter('tier','難易度',['FOUNDATION','STANDARD','APPLIED','PRACTICAL'],tier)}<label>問題（${eligible.length}題）<select id="bank-problem">${eligible.map(p=>`<option value="${p.id}" ${p.id===selected?'selected':''}>${p.variantId} / ${p.familyId} / ${p.difficultyTier}</option>`).join('')}</select></label>${p?`<section class="problem-paper"><p class="math-text">${esc(p.prompt)}</p></section><button class="primary" data-action="bank-preview">この問題を紙に解く・提出へ</button><p>提出後に答え・解説・グラフと内部検証情報を確認できます。</p>`:'<p>この条件の問題はありません。</p>'}<details class="panel"><summary>除外候補・重複チェック</summary>${json(bankArtifact.rejected)}${json(bankArtifact.audit)}</details><button class="secondary" data-action="home">学習画面へ戻る</button></section>`;
}
export function bindBank(root:HTMLElement,render:()=>void){for(const input of root.querySelectorAll<HTMLSelectElement>('[data-bank-filter]'))input.addEventListener('change',()=>{if(input.dataset.bankFilter==='family')family=input.value;if(input.dataset.bankFilter==='step')step=input.value;if(input.dataset.bankFilter==='tier')tier=input.value;render();});root.querySelector<HTMLSelectElement>('#bank-problem')?.addEventListener('change',e=>{selected=(e.target as HTMLSelectElement).value;render();});}
