import {tratioBankArtifact as artifact,tratioBankById,tratioBankRecords,tratioMaxRecords,productionTratioPaperSpecs} from './catalog.ts';
import {normalTratio,tratioSteps,tratioSkills} from '../tratio/lessons.ts';
import type {TratioBankRecord} from './types.ts';
import {shuffledChoices} from '../grading/paper-choices.ts';
import type {PaperChoice} from '../grading/paper-choices.ts';
const esc=(v:unknown)=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const json=(v:unknown)=>`<pre class="bank-json">${esc(JSON.stringify(v,null,2))}</pre>`;
export function tratioBankExplanation(p:TratioBankRecord){return `<section class="explanation"><h2>考え方</h2><p>${esc(p.explanation.thinking)}</p><h2>解き方</h2>${p.explanation.steps.map(s=>`<p>${esc(s)}</p>`).join('')}<h2>図で確かめる</h2>${p.solutionFigure}<h2>答え</h2><p class="answer-example">${esc(p.answer)}</p></section>`;}
export function tratioBankDetails(p:TratioBankRecord,choiceId?:string){return `<details class="panel"><summary>TRATIO本番データの検証情報</summary>${json({status:p.reviewStatus,familyId:p.familyId,variantId:p.variantId,structureSignature:p.structureSignature,difficulty:p.difficultyTier,Skill:p.skillId})}<h3>必要能力・CrossSkill</h3>${json(p.problemRequirements)}<h3>今回の弱点仮説（確定ではありません）</h3>${json(p.choices.find(c=>c.choiceId===choiceId)?.hypothesis??null)}<h3>選択肢・誤答候補の採用と除外</h3>${json(p.choices)}${json(p.candidateAudit)}<h3>数学モデル・solutionTrace</h3>${json(p.parameters)}${json(p.solutionTrace)}<h3>独立oracle・検証</h3>${json(p.oracle)}${json(p.validation)}</details>`;}
let selected=tratioBankRecords[0].id,step='',family='',difficulty='',skill='',max=false,phase:'problem'|'choices'|'result'='problem',chosen='',ordered:PaperChoice[]=[];
export const selectedTratioBank=()=>selected;
export function renderTratioBank(){
 const rows=(max?tratioMaxRecords:tratioBankRecords).filter(p=>(!step||String(p.step)===step)&&(!family||p.familyId===family)&&(!difficulty||p.difficultyTier===difficulty)&&(!skill||p.skillId===skill));
 if(!rows.some(p=>p.id===selected)){selected=rows[0]?.id??'';phase='problem';}
 const p=tratioBankById.get(selected);
 const filter=(key:string,label:string,values:string[],value:string)=>`<label>${label}<select data-trbank-filter="${key}"><option value="">すべて</option>${values.map(v=>`<option ${v===value?'selected':''} value="${esc(v)}">${esc(v)}</option>`).join('')}</select></label>`;
 return `<section class="bank-review tratio-production"><h1>三角比 本番問題バンク</h1><p>通常70題：reviewed 22題＋verified-generated 48題。修復2題・固定MAX3題は別枠です。</p><details class="panel"><summary>件数・構造一覧</summary>${json({reviewed:normalTratio.length,generated:48,normal:70,repair:2,max:3,generatedCounts:artifact.audit.counts,normalStepCounts:tratioSteps.map(t=>({step:t.number,reviewed:normalTratio.filter(l=>l.step===t.number).length,generated:tratioBankRecords.filter(p=>p.step===t.number).length})),normalSkillCounts:tratioSkills.map(([id])=>({skill:id,reviewed:normalTratio.filter(l=>l.problem.skillId===id).length,generated:tratioBankRecords.filter(p=>p.skillId===id).length})),structureSignatures:artifact.audit.signatures,exceptions:artifact.audit.signatureExceptions})}</details><button class="secondary" data-action="tratio-open">reviewed教材と修復教材を確認</button><button class="secondary" data-trbank-action="practice">通常バンク48題</button><button class="secondary" data-trbank-action="max">固定MAX3候補</button><p>${max?'MAX：6択と厳格な紙答案確認を使います。':'通常練習：4択。初見の技能ではreviewed教材から始めます。'}</p>${filter('step','STEP',['2','3','4'],step)}${filter('family','Family',[...new Set((max?tratioMaxRecords:tratioBankRecords).map(p=>p.familyId))],family)}${filter('difficulty','難度',['STANDARD','APPLIED','PRACTICAL'],difficulty)}${filter('skill','Skill',[...new Set((max?tratioMaxRecords:tratioBankRecords).map(p=>p.skillId))],skill)}<label>問題<select id="trbank-problem">${rows.map(p=>`<option value="${p.id}" ${p.id===selected?'selected':''}>${p.id} · ${p.difficultyTier}</option>`).join('')}</select></label>${p?`<h2>${max?'固定MAX候補':'練習問題'}</h2><section class="problem-paper"><p class="math-text">${esc(p.prompt)}</p></section>${phase==='result'?`<h2>${p.choices.find(c=>c.choiceId===chosen)?.correct?'最終結論は正しいです':'最終結論は未解決です'}</h2><p>この確認画面では習熟・MAXを更新しません。</p>${tratioBankExplanation(p)}${tratioBankDetails(p,chosen)}<button class="secondary" data-trbank-action="restart">最初から確認する</button>`:p.problemFigure+(phase==='problem'?'<button class="primary" data-trbank-action="choices">紙に解いたので選択肢へ</button>':`<fieldset class="answer-options"><legend>最終答案</legend>${ordered.map(c=>`<label><input type="radio" name="trbank-choice" value="${c.choiceId}"/><span>${esc(c.text)}</span></label>`).join('')}</fieldset><button class="primary" data-trbank-action="submit">提出する</button>`)}<button class="secondary" data-action="trbank-preview">学習フローで確認（専用デモ）</button>`:'<p>該当する問題はありません。</p>'}<p>通常学習の保存データは変更しません。</p><button class="secondary" data-action="home">学習画面へ戻る</button></section>`;
}
export function bindTratioBank(root:HTMLElement,render:()=>void){
 for(const input of root.querySelectorAll<HTMLSelectElement>('[data-trbank-filter]'))input.addEventListener('change',()=>{const k=input.dataset.trbankFilter;if(k==='step')step=input.value;if(k==='family')family=input.value;if(k==='difficulty')difficulty=input.value;if(k==='skill')skill=input.value;phase='problem';render();});
 root.querySelector<HTMLSelectElement>('#trbank-problem')?.addEventListener('change',e=>{selected=(e.target as HTMLSelectElement).value;phase='problem';render();});
 for(const b of root.querySelectorAll<HTMLButtonElement>('[data-trbank-action]'))b.addEventListener('click',()=>{const a=b.dataset.trbankAction;if(a==='practice'||a==='max'){max=a==='max';step=family=difficulty=skill='';phase='problem';}if(a==='choices'){ordered=shuffledChoices(productionTratioPaperSpecs[selected]);phase='choices';}if(a==='submit'){const c=root.querySelector<HTMLInputElement>('input[name="trbank-choice"]:checked');if(!c)return;chosen=c.value;phase='result';}if(a==='restart')phase='problem';render();});
}
