import {generateAxisProblem} from './quadratic-axis-family.ts';
import type {AxisAnswer} from './quadratic-axis-family.ts';
import {countModel,countGraphState} from './quadratic-count-family.ts';
import type {CountParameters} from './quadratic-count-family.ts';
import {familyModel} from './quadratic-family.ts';
import {placementModel,generatePlacementProblem,rootPlacementOracle,placementGraphState,evaluate,polynomialText,fraction,setText,targetText} from './quadratic-placement-family.ts';
import type {PlacementParameters,PlacementSet} from './quadratic-placement-family.ts';
import {extremaComponent,extremaOracle,extremaGraph,constrainExtrema,evaluateCases,add,times,constant,expressionText,expressionAt,solve,relation,intersectSets,unionSets,answerText,equivalentAnswers,setBoundaries,allBoundaries,placementBoundaries,contains,casesText} from './integrated-quadratic-math.ts';
import type {QuadraticExpression,ExtremaComponent,ExtremaConstraint,IntegratedAnswer} from './integrated-quadratic-math.ts';
import type {DynamicBoundary} from '../ui/dynamic-quadratic.ts';
import type {ExplanationGraph,Polynomial} from '../ui/explanation-graph.ts';

export type TraceKind='InterpretPrompt'|'PreserveDomain'|'CompleteSquare'|'ReadAxis'|'GenerateCandidates'|'SplitParameterCases'|'CompareValues'|'EqualYValues'|'MoveToDifferenceEquation'|'ChooseDiscriminant'|'SolveParameterCondition'|'CheckRootPlacement'|'IntersectConditions'|'VerifyOriginal'|'Conclude';
export interface SolutionStep {kind:TraceKind;explanation:string;result:unknown}
interface Requirement {id:string;description:string;crossSkills:string[]}
export interface IntegratedCandidate {type:string;answer:IntegratedAnswer;diagnosticScore:number;reason:string;hypothesis:string;crossSkills:string[];errorModel:unknown}
interface IntegratedModels {extrema?:ExtremaComponent;intersection?:ReturnType<typeof countModel>;placement?:ReturnType<typeof placementModel>;horizontal?:ReturnType<typeof familyModel>;extraConditions?:{name:string;set:PlacementSet}[];constraints?:ExtremaConstraint[]}
interface Draft {index:number;level:'標準'|'応用'|'実戦';prompt:string;structureSignature:string[];models:IntegratedModels;trace:SolutionStep[];thinking:string;answer:IntegratedAnswer;candidates:IntegratedCandidate[];boundaries:DynamicBoundary[];initial:number;graphs:(k:number)=>ExplanationGraph[];dynamic:boolean;oracle:(k:number)=>{satisfied:boolean;details:unknown};}
const step=(kind:TraceKind,explanation:string,result:unknown):SolutionStep=>({kind,explanation,result});
const req=(id:string,description:string,crossSkills:string[]):Requirement=>({id,description,crossSkills});
function requirements(d:Draft){const kinds=new Set(d.trace.map(s=>s.kind));return [req('interpret','求める結論に必要な道具を自分で選ぶ',['X11']),...(kinds.has('CompleteSquare')?[req('representation','軸と頂点を読める形へ同値変形する',['X05','X08'])]:[]),...(kinds.has('PreserveDomain')?[req('domain','指定区間内で候補を選ぶ',['X03'])]:[]),...(kinds.has('GenerateCandidates')?[req('candidates','両端と区間内の頂点を不足なく比較する',['X07'])]:[]),...(kinds.has('SplitParameterCases')?[req('cases','境界を導き、全範囲を漏れなく扱う',['X06'])]:[]),...(kinds.has('EqualYValues')?[req('intersection','共有点を等式・差の方程式として表す',['X08','X10'])]:[]),...(kinds.has('ChooseDiscriminant')?[req('discriminant','判別式と異なる根・重解を対応させる',['X12'])]:[]),...(kinds.has('CheckRootPlacement')?[req('placement','個数だけでなく根の位置を確かめる',['X04'])]:[]),...(kinds.has('IntersectConditions')?[req('intersection_sets','複数条件の共通部分を求める',['X04'])]:[]),req('verify','境界・等号を元条件に戻して確認する',['X13'])];}
function finish(d:Draft){const id=`QF-FAMILY-INTEGRATED-${String(d.index).padStart(2,'0')}`,chosen:IntegratedCandidate[]=[];
 const decisions=[...d.candidates].sort((a,b)=>b.diagnosticScore-a.diagnosticScore||a.type.localeCompare(b.type)).map(c=>{const duplicate=chosen.find(x=>equivalentAnswers(x.answer,c.answer));const exclusion=equivalentAnswers(c.answer,d.answer)?'正答と数学的に同値':duplicate?`採用候補 ${duplicate.type} と数学的に同値`:chosen.length===3?'この問題で診断価値が高い3候補を優先':'';if(!exclusion)chosen.push(c);return {...c,selected:!exclusion,selectionReason:exclusion||c.reason};});
 const choice=(c:IntegratedCandidate|null)=>({choiceId:`${id}:${c?.type??'correct'}`,correct:!c,answer:c?.answer??d.answer,text:answerText(c?.answer??d.answer),mistakeType:c?.type??null,mistakeHypotheses:c?[{mistakeType:c.type,description:c.hypothesis,crossSkills:c.crossSkills,weaknessTags:[c.type],hypothesisOnly:true as const}]:[]});
 if(chosen.length!==3)throw new Error(`Need three meaningful distinct integrated errors: ${id}`);
 const trace=[...d.trace,step('Conclude',answerText(d.answer),d.answer)];
 return {...d,id,status:'prototype-unreviewed' as const,solutionTrace:trace,problemRequirements:requirements(d),decisions,choices:[choice(null),...chosen.map(choice)],explanation:{thinking:d.thinking,steps:trace.filter(s=>s.kind!=='InterpretPrompt'&&s.kind!=='Conclude').map(s=>s.explanation),answer:answerText(d.answer)}};
}
const setAnswer=(set:PlacementSet):IntegratedAnswer=>({kind:'set',set});
const candidate=(type:string,answer:IntegratedAnswer,diagnosticScore:number,reason:string,hypothesis:string,crossSkills:string[],errorModel:unknown):IntegratedCandidate=>({type,answer,diagnosticScore,reason,hypothesis,crossSkills,errorModel});
const valuesAnswer=(answer:AxisAnswer,k:number):IntegratedAnswer=>{const v=evaluateCases(answer,k);return {kind:'values',min:v.min[0],max:v.max[0]};};
const constraintText=(c:ExtremaConstraint)=>`${c.key==='min'?'最小値':'最大値'}${c.op==='eq'?'=':c.op==='ge'?'≧':'≦'}${c.value}`;
function constraintHolds(c:ExtremaConstraint,value:number){return c.op==='eq'?Math.abs(value-c.value)<1e-8:c.op==='ge'?value>=c.value-1e-8:value<=c.value+1e-8;}
interface ExtSeed {index:number;level:Draft['level'];expression:QuadraticExpression;L:number;R:number;mode:'fixed'|'cases'|'inverse';constraints?:ExtremaConstraint[];placement?:PlacementParameters;prompt?:string;signature:string[]}
function makeExtrema(s:ExtSeed){
 const c=extremaComponent(s.expression,s.L,s.R),constraints=s.constraints??[],placement=s.placement?placementModel(s.placement):undefined;
 const conditionSets=constraints.map(r=>({name:constraintText(r),set:constrainExtrema(c,r)}));if(placement)conditionSets.push({name:targetText(placement.parameters.target),set:placement.answer});
 const convert=(a:AxisAnswer):IntegratedAnswer=>s.mode==='fixed'?valuesAnswer(a,0):s.mode==='cases'?{kind:'cases',cases:a}:setAnswer(intersectSets([...constraints.map(r=>constrainExtrema(c,r,a)),...(placement?[placement.answer]:[])]));
 const answer=convert(c.answer),wrongAxis=generateAxisProblem(c.base.parameters,1).decisions.filter(d=>s.mode!=='fixed'||!['case_missing','case_boundary_missing','boundary_equality'].includes(d.type));
 const candidates=wrongAxis.map(d=>candidate(d.type,convert(c.liftAnswer(d.choice.answer)),d.diagnosticScore+(s.mode==='inverse'&&d.type.includes('endpoint')?15:0),d.reason,d.choice.mistakeHypotheses[0].description,d.choice.mistakeHypotheses[0].crossSkills,{source:'family2',axisAnswer:d.choice.answer,lifted:c.liftAnswer(d.choice.answer)}));
 const oppositeAxis=extremaComponent({...s.expression,B:times(s.expression.B,-1)},s.L,s.R);
 candidates.push(candidate('complete_square_sign',convert(oppositeAxis.answer),c.axis[1]===0?110:92,'平方完成で軸の符号を逆に読んだ放物線を、指定区間で最後まで評価する','平方完成した式と軸の符号の対応が不安定な可能性',['X08'],oppositeAxis));
 if(s.mode==='fixed')candidates.push(candidate('domain_ignored',{kind:'values',min:s.expression.A===1?evaluate(c.vertical,0):-Infinity,max:s.expression.A===-1?evaluate(c.vertical,0):Infinity},106,'指定区間を落として、実数全体での最大最小を答える','平方完成後に元の定義域を参照していない可能性',['X03'],{domain:'all real',vertex:c.vertical}));
 if(s.mode==='inverse'&&conditionSets.length>1){conditionSets.forEach((cs,i)=>candidates.push(candidate(`condition_omitted_${cs.name}`,setAnswer(intersectSets(conditionSets.filter((_,j)=>j!==i).map(x=>x.set))),105,`「${cs.name}」を使わず、残りの条件だけで結論を出す`,`「${cs.name}」を最後まで引き継いでいない可能性`,['X04'],{omitted:cs.name,remaining:conditionSets.filter((_,j)=>j!==i)})));candidates.push(candidate('union_instead_of_intersection',setAnswer(unionSets(conditionSets.map(x=>x.set))),104,'個々の条件は解くが、共通部分の代わりに和集合を取る','個別条件を同時に満たす範囲の扱いが不安定な可能性',['X04'],{operation:'union',conditionSets}));}
 const trace=[step('InterpretPrompt','指定された区間で、求める値または値の条件を確認します。',{mode:s.mode,constraints}),step('PreserveDomain',`定義域は${s.L}≦x≦${s.R}です。式から得た頂点を使えるかどうかも、この区間に戻して判断します。`,{L:s.L,R:s.R}),step('CompleteSquare',`一般形を平方完成すると、f(x)=${c.completedSquare}です。展開すれば元の${expressionText(s.expression)}に戻り、グラフの位置を読める形になります。`,{original:s.expression,axis:c.axis,vertical:c.vertical}),step('ReadAxis',`軸はx=${polynomialText(c.axis)}、頂点の高さは${polynomialText(c.vertical)}です。${s.expression.A===1?'上':'下'}に開くので、軸に近いほど値は${s.expression.A===1?'小さく':'大きく'}なります。`,{axis:c.axis,vertical:c.vertical}),step('GenerateCandidates',`左右の端点x=${s.L}, ${s.R}を必ず候補にします。頂点は${s.L}≦${polynomialText(c.axis)}≦${s.R}を満たすときだけ候補に加えます。`,{left:c.left,right:c.right,domain:[s.L,s.R]})];
 if(c.boundaries.length)trace.push(step('SplitParameterCases',`軸が端点を通るときと、両端までの距離が等しいときで候補が変わります。境界は${c.boundaries.map(b=>`k=${b.label}`).join('、')}です。一つに決められないので、境界を含めて全範囲を分けます。`,{boundaries:c.boundaries,cases:c.answer}));
 trace.push(step('CompareValues',s.mode==='fixed'?`候補の値を比較すると、${answerText(answer)}です。頂点だけを見るのではなく、両端の値と比べて結論を出します。`:`各場合で候補を元の式に代入して比較すると、次のようになります。\n${casesText(c.answer)}`,c.answer));
 for(const cs of conditionSets.slice(0,constraints.length))trace.push(step('SolveParameterCondition',`求めたいのは「${cs.name}」となるkです。上の各場合の式をこの条件に当てはめ、その式を使えるkの範囲とも共通部分を取ると、${setText(cs.set)}となります。`,cs));
 if(placement)trace.push(step('CheckRootPlacement',`さらに、根が${targetText(placement.parameters.target)}である必要があります。${placement.conditions.map(c=>`${c.label}、すなわち${polynomialText(c.polynomial)}${c.inclusive?'≧':'>'}0`).join('、')}から、${setText(placement.answer)}です。${placement.parameters.target.kind==='straddle'?'指定点が2根の間なら、開き方向と反対の符号になります。':'軸は2根の平均なので、端点の符号と合わせて2根の位置を確かめます。'}`,placement));
 if(conditionSets.length>1)trace.push(step('IntersectConditions',`これらはすべて同時に満たす条件です。共通部分を取ると、${answerText(answer)}となります。`,{conditionSets,answer}));
 trace.push(step('VerifyOriginal',`元の定義域${s.L}≦x≦${s.R}に戻ります。端点は常に含まれ、頂点は区間内にある場合だけ使っています。${constraints.length?'得たkを各場合の元の式へ戻すと、'+constraints.map(constraintText).join('、')+'を同時に満たします。':''}${placement?'根についても実際の2根を元の配置条件へ代入して確認します。':''}境界では隣り合う式の値が一致し、等号を含める条件の境界も落としていません。`,{domain:[s.L,s.R],constraints,target:placement?.parameters.target}));
 const prompt=s.prompt??`kを実数とする。f(x)=${expressionText(s.expression)}、${s.L}≦x≦${s.R}について、${s.mode==='inverse'?constraints.map(constraintText).join('、')+'となるkの範囲': '最大値と最小値'+(s.mode==='cases'?'をkで表したもの':'')}を求めよ。`;
 const bounds=allBoundaries(c.boundaries,...conditionSets.map(x=>setBoundaries(x.set)),...(placement?[placement.boundaries]:[]));
 return finish({index:s.index,level:s.level,prompt,structureSignature:s.signature,models:{extrema:c,placement,constraints,extraConditions:conditionSets},trace,thinking:'求めたい結論には、軸と指定区間の位置関係が関わります。今の式では軸を読み取りにくいので、頂点の形に直します。頂点と両端のうち、区間内でどの点が値を決めるかを考えます。'+(s.mode==='inverse'?'値そのものを求めて終わらず、指定された値になる条件を逆にkへ読み替えます。':''),answer,candidates,boundaries:bounds,initial:s.mode==='fixed'?0:1,graphs:k=>[extremaGraph(c,k)],dynamic:c.axis[1]!==0,oracle:k=>{const v=extremaOracle(c,k),root=s.placement?rootPlacementOracle(s.placement,k):undefined;return {satisfied:constraints.every(r=>constraintHolds(r,v[r.key]))&&(!root||root.satisfied),details:{...v,root,originalConstraints:constraints}};}});
}
const countBase:CountParameters={A:1,p:0,q:1,kind:'slope',slope:2,intercept:0,pivotX:0,target:2,level:'高め'};
function countTrace(m:ReturnType<typeof countModel>):SolutionStep[]{
 const roots=placementBoundaries(m.D),positive=solve([relation('D_positive',m.D,false)]);
 return [step('EqualYValues',`共有点では二つのy座標が等しいので、${m.equation}とおきます。`,{f:m.f,lineSlope:m.lineSlope,lineIntercept:m.lineIntercept}),step('MoveToDifferenceEquation',`差を取ると${m.zeroEquation}です。この方程式の実根が共有点のx座標になります。`,{A:m.A,B:m.B,C:m.C}),step('ChooseDiscriminant',`まず共有点の個数を判断します。差の方程式の判別式はD=${polynomialText(m.D)}。異なる2点ならD>0、接するならD=0です。個数の条件に応じてこの道具を選びます。`,{D:m.D}),...(m.parameters.target===2?[step(roots.length===2&&m.D[0]!==0?'SplitParameterCases':'SolveParameterCondition',`D=0となる境界は${roots.map(b=>'k='+b.label).join('、')}です。境界の間と外側の符号を調べると、D>0を満たすのは${setText(positive)}です。境界そのものは重解なので含めません。`,{roots,positive})]:[])];
}
function placementErrors(m:ReturnType<typeof placementModel>,extra:PlacementSet[]):IntegratedCandidate[]{return generatePlacementProblem(m.parameters,1).decisions.map(d=>candidate(d.type,setAnswer(intersectSets([d.choice.answer,...extra])),d.diagnosticScore,d.reason,d.choice.mistakeHypotheses[0].description,d.choice.mistakeHypotheses[0].crossSkills,{source:'family4',model:d.errorModel,extra}));}
function makeIntersection(index:5|7|10){
 const isHorizontal=index===7,cm=isHorizontal?undefined:countModel(index===5?countBase:{...countBase,p:-2,q:2,kind:'pivot',pivotX:1,intercept:0});
 const horizontal=isHorizontal?familyModel({h:2,c:-1,L:0,R:4,leftClosed:true,rightClosed:true}):undefined;
 const pp:PlacementParameters=isHorizontal?{A:1,b1:0,b0:-4,c1:-1,c0:3,target:{kind:'inside',L:0,R:4,leftClosed:true,rightClosed:true},level:'高め'}:{A:1,b1:cm!.B[1],b0:cm!.B[2],c1:cm!.C[1],c0:cm!.C[2],target:index===5?{kind:'right',r:0}:{kind:'inside',L:0,R:4,leftClosed:true,rightClosed:false},level:'高め'};
 const pm=placementModel(pp),extra=index===5?solve([relation('sum_less_than_three',[0,-1,3],false)]):index===7?solve([relation('distance_at_least_two',add(pm.D,constant(-4)),true)]):solve([]),set=intersectSets([pm.answer,extra]),answer=setAnswer(set);
 const extraName=index===5?'2つのx座標の和が3未満':index===7?'2つのx座標の差が2以上':'指定区間の開閉';
 const candidates=placementErrors(pm,index===10?[]:[extra]);
 if(index!==10){candidates.push(candidate('extra_condition_omitted',setAnswer(pm.answer),111,`${extraName}を使わず、共有点の配置だけで答える`,`${extraName}を最後まで引き継いでいない可能性`,['X04'],{placement:pm.answer}));candidates.push(candidate('union_instead_of_intersection',setAnswer(unionSets([pm.answer,extra])),110,'配置条件と追加条件を同時に満たさず、和集合を取る','個別条件は解けても共通部分で誤る可能性',['X04'],{placement:pm.answer,extra,operation:'union'}));}
 const wrongMove=placementModel({...pp,b1:-pp.b1,c1:-pp.c1});candidates.push(candidate('move_sign_error',setAnswer(intersectSets([wrongMove.answer,extra])),102,'直線のkを含む項を移項しても符号を変えず、誤った差の方程式から配置を判定する','共有点の等式から差を作るときの符号処理が不安定な可能性',['X05'],wrongMove));
 const trace:SolutionStep[]=[step('InterpretPrompt','求めるのは共有点の個数だけでなく、そのx座標について指定された条件を満たすkです。',{target:pp.target,extraName}),...(cm?countTrace(cm):[step('EqualYValues',`共有点ではx²−4x+3=kです。平方完成すると(x−2)²=k+1となり、2つのx座標は2−√(k+1)、2+√(k+1)です。`,horizontal!),step('MoveToDifferenceEquation','同じ等式を左辺に集めるとx²−4x+3−k=0です。元の2つのグラフの共有点を、この式の実根として扱えます。',{A:pm.A,B:pm.B,C:pm.C})]),step('CheckRootPlacement',`D>0だけでは、2つの根の位置までは分かりません。${pm.parameters.target.kind==='right'?'軸が0より右にあり、0が2根の外側にあることも必要です。':'平均である軸が区間内にあり、左右端点が2根の外側にあることを確認します。'}${pm.conditions.map(c=>`${c.label}から${setText(c.set)}`).join('。')}。これらを合わせると${setText(pm.answer)}です。`,pm)];
 if(index!==10)trace.push(step('SolveParameterCondition',index===5?`差の方程式の2根の和は−B/A=kです。和が3未満という条件から、${setText(extra)}を得ます。`:`2つのx座標の差は2√(k+1)です。これが2以上となるには√(k+1)≧1、つまり${setText(extra)}が必要です。平方根は0以上なので、この変形で余分な解は入りません。`,{extraName,set:extra}));
 trace.push(step('IntersectConditions',`元の条件をすべて同時に満たす範囲は、${setText(set)}です。${index===10?'右端x=4は含まないため、その端点に根が来る境界の等号は付けません。':'個数・位置だけで止めず、追加条件との共通部分を取ります。'}`,{placement:pm.answer,extra,answer}),step('VerifyOriginal',`元の二つのグラフへ戻り、差の方程式の2根をそれぞれ代入すると同じy座標になります。${index===5?'両方のx座標が正で、その和も3未満です。':index===7?'両方のx座標が0以上4以下で、その差も2以上です。':'両方のx座標が0以上4未満です。'}D=0では異なる2点にならないので除き、端点や追加条件の等号は問題文どおりに扱います。`,{target:pp.target,extraName}));
 const prompts={5:'kを実数とする。y=x²+1とy=kxが異なる2点で交わり、両方のx座標が正で、その和が3未満となるkの範囲を求めよ。',7:'kを実数とする。y=x²−4x+3とy=kが異なる2点で交わる。そのx座標がともに0以上4以下で、2つのx座標の差が2以上となるkの範囲を求めよ。',10:'kを実数とする。y=x²−2x+2とy=k(x−1)が異なる2点で交わり、両方のx座標が0以上4未満となるkの範囲を求めよ。'};
 return finish({index,level:index===10?'実戦':'応用',prompt:prompts[index],structureSignature:index===5?['INTERSECTION','DISCRIMINANT','ROOT_SUM','POSITIVE_ROOTS']:index===7?['REP_CHANGE','INTERSECTION','ROOT_INTERVAL','DISTANCE']:['INTERSECTION','FIXED_POINT_LINE','ROOT_PLACEMENT','HALF_OPEN'],models:{intersection:cm,placement:pm,horizontal,extraConditions:[{name:extraName,set:extra}]},trace,thinking:'共有点に指定された条件を、x座標についての条件へ読み替えます。二つの式を等しいとおけば、個数と位置を同じ方程式で調べられます。'+(index===7?'平方完成した形なら、2つの根の間隔も読み取りやすくなります。':'実根が2つあることと、その2根が指定位置にあることを分けて考えます。'),answer,candidates,boundaries:allBoundaries(pm.boundaries,setBoundaries(extra)),initial:index===5?2.5:index===7?1:3,dynamic:index!==5,graphs:k=>{if(index===5)return [];if(cm){const g=countGraphState(cm.parameters,k);return [g.original,g.difference];}const g=placementGraphState(pp,k),f:Polynomial=[1,-4,3];return [{...g.graph,title:'放物線と水平線の共有点',curves:[{formula:'y=x²−4x+3',coefficients:f},{formula:'y=k',coefficients:[0,0,k]}],view:[-1,5,-3,8],caption:'共有点が指定区間に入り、2つのx座標の差が2以上かを確かめます。'},g.graph];},oracle:k=>{const root=rootPlacementOracle(pp,k);const extraOK=index===5?root.roots.length===2&&root.roots[0]+root.roots[1]<3-1e-9:index===7?root.roots.length===2&&root.roots[1]-root.roots[0]>=2-1e-9:true;return {satisfied:root.satisfied&&extraOK,details:{root,extraOK,originalGraphs:cm?{f:cm.f,slope:evaluate(cm.lineSlope,k),intercept:evaluate(cm.lineIntercept,k)}:{f:[1,-4,3],horizontal:k}}};}});
}
function makeTangent(){
 const m=countModel({...countBase,intercept:-1,target:1}),zero=solve([relation('D_ge',m.D,true),relation('D_le',times(m.D,-1),true)]),positive=solve([relation('positive_contact_x',[0,1,0],false)]);
 const build=(D:Polynomial,restrict:boolean,pointMode:'original'|'difference'|'missing_two'='original'):IntegratedAnswer=>({kind:'tangent',points:placementBoundaries(D).filter(b=>!restrict||b.value>0).map(k=>{const x=k.value/(pointMode==='missing_two'?1:2),xLabel=pointMode==='missing_two'?k.label:k.label.replace(/^2√/,'√').replace(/^−2√/,'−√'),y=pointMode==='difference'?0:evaluate(m.f,x);return {k,x,xLabel,y:Math.round(y*1e10)/1e10};})});
 const answer=build(m.D,true),candidates=[candidate('original_condition_omitted',build(m.D,false),111,'接するkを求めたあと、接点のx座標が正という条件を使わない','方程式から得た候補を元の接点条件で絞れていない可能性',['X13'],{D:m.D,restrict:false}),candidate('difference_point_as_original',build(m.D,true,'difference'),108,'差のグラフとx軸の接点を、そのまま元の2グラフの接点として答える','差のグラフから元のy座標へ戻れていない可能性',['X13'],{pointMode:'difference'}),candidate('axis_denominator_missing',build(m.D,true,'missing_two'),95,'接点のx座標を−B/Aとして求め、元の放物線へ代入する','軸の式の分母2Aの扱いが不安定な可能性',['X05'],{pointMode:'missing_two'}),candidate('discriminant_calculation_sign',build([1,0,8],true),103,'判別式をB²+4ACと計算し、その零点を求める','判別式の−4ACの符号処理が不安定な可能性',['X05'],{D:[1,0,8]})];
 const trace=[step('InterpretPrompt','接するkだけでなく、その接点が指定された側にあることと座標まで求めます。',{contactX:'positive'}),...countTrace(m),step('SolveParameterCondition',`接するときはD=0なので、${setText(zero)}です。接点のx座標は重解−B/(2A)=k/2。これが正という条件から${setText(intersectSets([zero,positive]))}に絞られます。`,{zero,positive,intersection:intersectSets([zero,positive])}),step('VerifyOriginal',`残ったkを元の放物線y=x²+1に代入してy座標を求めると、${answerText(answer)}です。この点は元の直線にも乗ります。差のグラフでのy=0を、元の接点のy座標としてはいけません。`,answer)];
 return finish({index:6,level:'応用',prompt:'kを実数とする。y=x²+1とy=kx−1が接し、その接点のx座標が正となるkと接点の座標を求めよ。',structureSignature:['INTERSECTION','TANGENCY','INVERSE','ORIGINAL_COORDINATES'],models:{intersection:m,extraConditions:[{name:'D=0',set:zero},{name:'接点x>0',set:positive}]},trace,thinking:'接するかどうかは、二つの式を等しいとおいた方程式が重解をもつかで判断できます。kが分かった後も、接点が指定された側にあるかを確認し、元の式からy座標を求める必要があります。',answer,candidates,boundaries:allBoundaries(placementBoundaries(m.D),[{value:0,label:'0'}]),initial:Math.sqrt(8),dynamic:true,graphs:k=>{const g=countGraphState(m.parameters,k);return [g.original,g.difference];},oracle:k=>{const b=-k,D=b*b-8,x=-b/2,y=x*x+1;return {satisfied:Math.abs(D)<1e-8&&x>0,details:{D,x,y,lineY:k*x-1,difference:y-(k*x-1)}};}});
}
const expr=(A:1|-1,B:Polynomial,C:Polynomial):QuadraticExpression=>({A,B,C});
export const integratedProblems=[
 makeExtrema({index:1,level:'標準',expression:expr(1,[0,0,-6],[0,0,5]),L:0,R:4,mode:'fixed',prompt:'f(x)=x²−6x+5について、0≦x≦4における最大値と最小値を求めよ。',signature:['REP_CHANGE','DOMAIN','VERTEX_AND_ENDPOINTS','EXTREMA']}),
 makeExtrema({index:2,level:'標準',expression:expr(-1,[0,0,6],[0,0,-5]),L:-1,R:2,mode:'fixed',prompt:'f(x)=−x²+6x−5について、−1≦x≦2における最大値と最小値を求めよ。',signature:['REP_CHANGE','DOMAIN','AXIS_OUTSIDE','ENDPOINTS']}),
 makeExtrema({index:3,level:'応用',expression:expr(1,[0,-2,0],[1,0,-1]),L:0,R:3,mode:'cases',prompt:'kを実数とする。f(x)=x²−2kx+k²−1について、0≦x≦3における最大値と最小値をkで表せ。',signature:['REP_CHANGE','MOVING_AXIS','CASE_SPLIT','EXTREMA']}),
 makeExtrema({index:4,level:'応用',expression:expr(-1,[0,2,0],[-1,0,2]),L:-1,R:2,mode:'inverse',constraints:[{key:'max',op:'eq',value:1}],prompt:'kを実数とする。f(x)=−x²+2kx−k²+2の−1≦x≦2における最大値が1となるkを求めよ。',signature:['REP_CHANGE','CASE_SPLIT','INVERSE_EXTREMUM','VERIFY']}),
 makeIntersection(5),makeTangent(),makeIntersection(7),
 makeExtrema({index:8,level:'実戦',expression:expr(1,[0,-2,0],[0,1,0]),L:-1,R:1,mode:'inverse',constraints:[{key:'min',op:'ge',value:-2}],placement:{A:1,b1:-2,b0:0,c1:1,c0:0,target:{kind:'straddle',r:0},level:'高め'},prompt:'kを実数とする。f(x)=x²−2kx+kについて、−1≦x≦1のすべてのxでf(x)≧−2となり、方程式f(x)=0が正の解と負の解を一つずつもつようなkの範囲を求めよ。',signature:['DOMAIN','UNIVERSAL_INEQUALITY','ROOT_PLACEMENT','INTERSECTION']}),
 makeExtrema({index:9,level:'実戦',expression:expr(1,[0,-2,0],[0,2,0]),L:0,R:3,mode:'inverse',constraints:[{key:'min',op:'ge',value:-1},{key:'max',op:'le',value:6}],prompt:'kを実数とする。0≦x≦3のすべてのxについて、−1≦x²−2kx+2k≦6が成り立つkの範囲を求めよ。',signature:['RANGE_CONTAINMENT','MOVING_VERTEX','TWO_EXTREMA','INTERSECTION']}),
 makeIntersection(10),
 makeExtrema({index:11,level:'実戦',expression:expr(-1,[0,1,0],[0,0,-1]),L:0,R:4,mode:'inverse',constraints:[{key:'max',op:'ge',value:3}],placement:{A:-1,b1:1,b0:0,c1:0,c0:-1,target:{kind:'inside',L:0,R:4,leftClosed:true,rightClosed:true},level:'高め'},prompt:'生産量xを0≦x≦4の連続量として、利益をP(x)=−x²+kx−1とする。利益の最大値が3以上で、利益が0となる生産量が異なる2つとも許容範囲内にあるような実数kの範囲を求めよ。',signature:['CONTEXT','INVERSE_PROFIT','ROOT_INTERVAL','INTERSECTION']}),
 makeExtrema({index:12,level:'実戦',expression:expr(1,[0,-2,0],[1,0,-1]),L:0,R:2,mode:'inverse',constraints:[{key:'min',op:'eq',value:-1},{key:'max',op:'eq',value:3}],prompt:'kを実数とする。0≦x≦2において、f(x)=x²−2kx+k²−1の値域がちょうど−1≦y≦3となるkをすべて求めよ。',signature:['EXACT_RANGE','INVERSE','TWO_EQUALITIES','EXHAUSTIVE']})
];
export type IntegratedQuadraticProblem=ReturnType<typeof finish>;
