import {unit,cos,sin,distance} from './math.ts';
import type {TratioFigure} from './types.ts';
export const esc=(v:unknown)=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const exact:Record<number,[string,string,string]>={0:['1','0','0'],30:['√3/2','1/2','√3/3'],45:['√2/2','√2/2','1'],60:['1/2','√3/2','√3'],90:['0','1','定義されない'],120:['−1/2','√3/2','−√3'],135:['−√2/2','√2/2','−1'],150:['−√3/2','1/2','−√3/3'],180:['−1','0','0']};
export function circleValues(theta:number){const p=unit(theta),labels=exact[theta]??[p.x.toFixed(3),p.y.toFixed(3),p.tan===null?'定義されない':p.tan.toFixed(3)];return {theta,...p,labels};}
export function unitCircle(theta:number){const p=circleValues(theta),x=155+105*p.x,y=153-105*p.y;return `<svg viewBox="0 0 310 282" role="img" aria-label="単位円。θ=${theta}度。cosはx座標、sinはy座標"><circle cx="155" cy="153" r="105" fill="#f5f9fc" stroke="#8799aa"/><path d="M20 153H292 M155 265V22" stroke="#697784"/><text x="294" y="166">x</text><text x="165" y="24">y</text><text x="141" y="169">O</text><text x="262" y="170">1</text><text x="35" y="170">−1</text><text x="161" y="44">1</text><path d="M155 153L${x} ${y}" stroke="#176b91" stroke-width="3"/><path d="M${x} ${y}V153 M${x} ${y}H155" stroke="#bc6139" stroke-dasharray="4 3" fill="none"/><path d="M182 153A27 27 0 0 0 ${155+27*cos(theta)} ${153-27*sin(theta)}" stroke="#176b91" fill="none"/><circle cx="${x}" cy="${y}" r="4" fill="#bc6139"/><text x="${Math.max(20,Math.min(245,x+5))}" y="${Math.max(18,y-9)}">P</text><text x="178" y="134">θ</text><text x="28" y="280">半径1：P=(cosθ, sinθ)</text></svg><p aria-live="polite">θ=${Number(theta.toFixed(3))}°<br>cosθ=${p.labels[0]}、sinθ=${p.labels[1]}<br>tanθ${p.tan===null?'は定義されない':'='+p.labels[2]}</p>`;}
export function figure(f:TratioFigure,interactive=false){if(f.kind==='unit'){const theta=f.theta??30;return `<figure class="tratio-figure">${interactive?`<div data-unit-circle><label>角θ（0〜180°）<input type="range" aria-label="単位円の角θ" min="0" max="180" step="1" value="${theta}"/></label><div class="boundary-buttons">${[0,30,60,90,120,150,180].map(a=>`<button type="button" data-tratio-angle="${a}">${a}°</button>`).join('')}</div><div data-circle-body>${unitCircle(theta)}</div></div>`:unitCircle(theta)}<figcaption>${esc(f.caption)} 図は理解の補助です。関係の根拠は式でも確かめます。</figcaption></figure>`;}
 const points=f.points??[],xs=[...points.map(p=>p.xy[0]),...(f.circle?[f.circle.center[0]-f.circle.radius,f.circle.center[0]+f.circle.radius]:[])],ys=[...points.map(p=>p.xy[1]),...(f.circle?[f.circle.center[1]-f.circle.radius,f.circle.center[1]+f.circle.radius]:[])],xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys),scale=Math.min(225/Math.max(1,xmax-xmin),175/Math.max(1,ymax-ymin)),X=(x:number)=>42+(x-xmin)*scale,Y=(y:number)=>215-(y-ymin)*scale,point=(name:string)=>points.find(p=>p.name===name)!;
 const edge=([a,b,label]:[string,string,string?],aux=false)=>{const p=point(a).xy,q=point(b).xy;return `<path d="M${X(p[0])} ${Y(p[1])}L${X(q[0])} ${Y(q[1])}" stroke="${aux?'#b96534':'#176b91'}" stroke-width="2" ${aux?'stroke-dasharray="5 4"':''}/>${label?`<text x="${(X(p[0])+X(q[0]))/2+4}" y="${(Y(p[1])+Y(q[1]))/2-6}">${esc(label)}</text>`:''}`;};
 const right=points.flatMap(p=>{const neighbors=(f.edges??[]).filter(e=>e[0]===p.name||e[1]===p.name).map(e=>point(e[0]===p.name?e[1]:e[0]).xy);return neighbors.flatMap((q,i)=>neighbors.slice(i+1).flatMap(r=>{const u=[q[0]-p.xy[0],q[1]-p.xy[1]],v=[r[0]-p.xy[0],r[1]-p.xy[1]],du=distance(p.xy,q),dv=distance(p.xy,r);if(Math.abs(u[0]*v[0]+u[1]*v[1])>1e-8)return [];const ax=X(p.xy[0])+u[0]/du*9,ay=Y(p.xy[1])-u[1]/du*9,bx=X(p.xy[0])+v[0]/dv*9,by=Y(p.xy[1])-v[1]/dv*9;return [`<path d="M${ax} ${ay}L${ax+v[0]/dv*9} ${ay-v[1]/dv*9}L${bx} ${by}" fill="none" stroke="#697784"/>`];}));}).join('');
 return `<figure class="tratio-figure"><svg viewBox="0 0 310 250" role="img" aria-label="${esc(f.caption)}">${f.circle?`<circle cx="${X(f.circle.center[0])}" cy="${Y(f.circle.center[1])}" r="${f.circle.radius*scale}" fill="none" stroke="#99aebb"/>`:''}${(f.edges??[]).map(e=>edge(e)).join('')}${(f.auxiliary??[]).map(e=>edge(e,true)).join('')}${right}${points.map(p=>`<circle cx="${X(p.xy[0])}" cy="${Y(p.xy[1])}" r="2.5" fill="#176b91"/><text x="${X(p.xy[0])-12}" y="${Y(p.xy[1])+17}">${esc(p.name)}</text>`).join('')}${(f.labels??[]).map(l=>`<text x="${X(l.at[0])}" y="${Y(l.at[1])}">${esc(l.text)}</text>`).join('')}</svg><figcaption>${esc(f.caption)} 破線は補助線です。長さ・角度は問題文の条件で判断してください。</figcaption></figure>`;
}
export function bindCircle(root:HTMLElement){for(const host of root.querySelectorAll<HTMLElement>('[data-unit-circle]')){const input=host.querySelector<HTMLInputElement>('input')!,body=host.querySelector<HTMLElement>('[data-circle-body]')!;const update=(theta:number)=>{input.value=String(theta);body.innerHTML=unitCircle(theta);};input.addEventListener('input',()=>update(Number(input.value)));for(const button of host.querySelectorAll<HTMLButtonElement>('[data-tratio-angle]'))button.addEventListener('click',()=>update(Number(button.dataset.tratioAngle)));}}
