import {tratioLessons,tratioSteps,tratioSkills,tratioById} from './lessons.ts';
import type {TratioLesson} from './types.ts';
import {figure,esc,bindCircle} from './figures.ts';
import {tratioAudit,tratioPaperSpecs} from './catalog.ts';
import {shuffledChoices} from '../grading/paper-choices.ts';
import type {PaperChoice} from '../grading/paper-choices.ts';
const lines=(s:string)=>esc(s).replaceAll('\n','<br>');
const json=(v:unknown)=>`<pre class="bank-json">${esc(JSON.stringify(v,null,2))}</pre>`;
export function tratioExplanation(l:TratioLesson){return `<section class="explanation"><h2>考え方</h2><p>${lines(l.thinking)}</p><h2>解き方</h2>${l.working.map(s=>`<p>${lines(s)}</p>`).join('')}${l.figure?'<h2>図で確かめる</h2>'+figure(l.figure,true):''}<h2>答え</h2><p class="answer-example">${lines(l.problem.answer)}</p></section>`;}
export function tratioSupport(l:TratioLesson){return `${l.introduction?`<details class="panel"><summary>はじめに：角と長さを結ぶ基準</summary><p>${lines(l.introduction)}</p><p>単位円上のPをP=(cosθ,sinθ)と定義します。cosθはx座標、sinθはy座標です。tanθ=y/x（x≠0）。半径を1にそろえることで、角を座標へ変える共通の基準になります。</p>${figure({kind:'unit',theta:30,caption:'θを動かし、点の座標の変化を確かめます。'},true)}</details>`:''}${l.figure?.essential?figure(l.figure):''}`;}
export function tratioDetails(l:TratioLesson,choiceId?:string){return `<details class="panel"><summary>三角比の検証情報</summary><p>STEP ${l.step} / ${esc(l.problem.skillId)} / ${l.kind==='max-prototype'?'MAX原型・検証専用（通常MAX判定には未接続）':'reviewed'}</p><h3>必要能力・CrossSkill</h3>${json(l.requirements)}<h3>今回の弱点仮説</h3>${json(l.choices.find(c=>c.choiceId===choiceId)?.hypothesis??null)}<h3>4択・誤答モデル・repair候補</h3>${json(l.choices.map(c=>({id:c.choiceId,text:c.text,correct:c.correct,hypothesis:c.hypothesis})))}<h3>個別数学チェック・独立計算</h3>${json(l.review)}${json(tratioAudit.find(a=>a.id===l.problem.id))}</details>`;}
let selected=tratioLessons[0].problem.id,step='',skill='',kind='',phase:'problem'|'choices'|'result'='problem',chosen='',ordered:PaperChoice[]=[];
export function renderTratio(){const rows=tratioLessons.filter(l=>(!step||String(l.step)===step)&&(!skill||l.problem.skillId===skill)&&(!kind||l.kind===kind));if(!rows.some(l=>l.problem.id===selected)){selected=rows[0]?.problem.id??'';phase='problem';}const l=tratioById.get(selected);
 const filter=(key:string,label:string,values:[string,string][],value:string)=>`<label>${label}<select data-tratio-filter="${key}"><option value="">すべて</option>${values.map(([v,n])=>`<option value="${v}" ${value===v?'selected':''}>${n}</option>`).join('')}</select></label>`;
 return `<section class="bank-review"><h1>図形と計量・三角比の教材確認</h1><p>新作reviewed通常22題・修復2題、MAX原型3題。旧TRATIOは教材の根拠にも出題にも使いません。</p><p>MAX原型は難度・時間の実測校正前です。この画面の正解ではMAXやTRIG解放を付与しません。通常MAXの既存3回・7日・1日1回ルールは変更していません。</p>${filter('step','STEP',tratioSteps.map(s=>[String(s.number),`${s.number} ${s.title}`]),step)}${filter('skill','Skill',tratioSkills.map(s=>[s[0],s[1]]),skill)}${filter('kind','教材区分',[['normal','通常reviewed'],['repair','短い修復'],['max-prototype','MAX原型']],kind)}<label>問題<select id="tratio-problem">${rows.map(l=>`<option value="${l.problem.id}" ${l.problem.id===selected?'selected':''}>${esc(l.problem.id)} · ${l.kind}</option>`).join('')}</select></label>${l?`<section class="problem-paper"><p class="math-text">${lines(l.problem.prompt)}</p></section>${phase==='problem'?`${tratioSupport(l)}<button class="primary" data-tratio-action="choices">紙に解いたので4択へ</button>${l.kind!=='max-prototype'?'<button class="secondary" data-action="tratio-preview">学習フローでも確認する（専用デモ）</button>':''}`:phase==='choices'?`<fieldset class="answer-options"><legend>紙答案の最終結果</legend>${ordered.map(c=>`<label><input type="radio" name="tratio-choice" value="${c.choiceId}"/><span>${lines(c.text)}</span></label>`).join('')}</fieldset><button class="primary" data-tratio-action="submit">この結論を提出する</button>`:`<h2>${l.choices.find(c=>c.choiceId===chosen)?.correct?'最終結論は正しいです':'最終結論は未解決です'}</h2><p>紙の途中式は未評価です。1回の誤答で弱点を確定しません。</p>${tratioExplanation(l)}${tratioDetails(l,chosen)}<button class="secondary" data-tratio-action="restart">同じ問題を最初から確認</button>`}`:'<p>この条件の教材はありません。</p>'}<p>この確認画面は通常学習・カルテを変更しません。</p><button class="secondary" data-action="home">学習画面に戻る</button></section>`;
}
export function selectedTratio(){return selected;}
export function bindTratio(root:HTMLElement,render:()=>void){bindCircle(root);for(const input of root.querySelectorAll<HTMLSelectElement>('[data-tratio-filter]'))input.addEventListener('change',()=>{const key=input.dataset.tratioFilter;if(key==='step')step=input.value;if(key==='skill')skill=input.value;if(key==='kind')kind=input.value;phase='problem';chosen='';render();});root.querySelector<HTMLSelectElement>('#tratio-problem')?.addEventListener('change',e=>{selected=(e.target as HTMLSelectElement).value;phase='problem';chosen='';render();});for(const b of root.querySelectorAll<HTMLButtonElement>('[data-tratio-action]'))b.addEventListener('click',()=>{if(b.dataset.tratioAction==='choices'){ordered=shuffledChoices(tratioPaperSpecs[selected]);phase='choices';}if(b.dataset.tratioAction==='submit'){const checked=root.querySelector<HTMLInputElement>('input[name="tratio-choice"]:checked');if(!checked)return;chosen=checked.value;phase='result';}if(b.dataset.tratioAction==='restart')phase='problem';render();});}
